- src/osg/OcclusionQueryNode.cpp
Thus avoiding a crash when osg::OcclusionQueryNode is used on systems that do not support occlusion queries.
> Check for presence of occlusion query extension

- src/osgPlugins/dae/daeWriter.cpp
As the title says this will fix the build on some more pedantic systems.
See also #61 which is fixed by this one.
> Added missing stdexcept header, fixes #61

- .travis.yml
You only need to login in travis and activate it for the osg github repo. There are only a few options in settings so it is pretty straight forward. Ping me if you have any problem setting it up.
> initial travis file, support for ubuntu trusty and osx builds

- src/osgPlugins/dae/daeRAnimations.cpp
- src/osgPlugins/dae/daeReader.cpp
OpenSceneGraph\src\osgPlugins\dae\daeRAnimations.cpp(470): warning C4456: declaration of 'kfCntr' hides previous local declaration
OpenSceneGraph\src\osgPlugins\dae\daeRAnimations.cpp(452): note: see declaration of 'kfCntr'
OpenSceneGraph\src\osgPlugins\dae\daeReader.cpp(202): warning C4456: declaration of 'i' hides previous local declaration
OpenSceneGraph\src\osgPlugins\dae\daeReader.cpp(188): note: see declaration of 'i'
OpenSceneGraph\src\osgPlugins\dae\daeReader.cpp(226): warning C4456: declaration of 'i' hides previous local declaration
OpenSceneGraph\src\osgPlugins\dae\daeReader.cpp(188): note: see declaration of 'i'
OpenSceneGraph\src\osgPlugins\dae\daeReader.cpp(243): warning C4456: declaration of 'i' hides previous local declaration …
> visual studio 2015 warning fixes:

- include/osgViewer/ViewerBase
- src/osgViewer/CompositeViewer.cpp
- src/osgViewer/Viewer.cpp
Sometimes there is need to do cleanup with valid graphic contexts before destroying these contexts. The added operation runs a graphics operation on each context before closing them.
> CleanUpOperation added to Viewer

- include/osg/Array
- include/osg/Quat
- include/osgAnimation/Animation
- include/osgAnimation/Keyframe
- src/osgAnimation/RigGeometry.cpp
- src/osgWrappers/serializers/osgAnimation/UpdateMorph.cpp
This updates is mainly for the gles plugint to work correctly.
* adds Quaternion array
* reintroduces `KeyframeContainer::linearInterpolationDeduplicate`
* fixes MorphGeometry OSG serialization (target names)
> Updates osgAnimation

- include/osgUtil/TriStripVisitor
- src/osgUtil/TriStripVisitor.cpp
This mainly breaks gles/osgjs when stripifying a MorphGeometry. It also
usually doesn't make sense to reindex an already indexed mesh.
> Adds an indexMesh option to disable mesh reindexation

- include/osgDB/DatabasePager
- include/osgViewer/Scene
- src/osgDB/DatabasePager.cpp
- src/osgPresentation/SlideEventHandler.cpp
- src/osgViewer/Scene.cpp
- src/osgViewer/View.cpp
would trigger unnecessary redraws when there were pending file requests or active database threads
tested ok with and without IncrementalCompileOperation
> streamline DatabasePager::requiresUpdateSceneGraph()

- src/osgUtil/TangentSpaceGenerator.cpp
@robertosfield it seems that this commit from Cedric was in the repo but disappeared at some point (see https://github.com/openscenegraph/OpenSceneGraph/commit/fbe98375d94876527ee2ce99d27e8467ad5aa7e6).
It mostly uses the same pass for geometry having no normal array and uses averages for tangent, binormal and normal.
> OsgUtil::TangentSpaceGenerator, merge tangent space for index array

- src/osg/FrameBufferObject.cpp
Commit 55b3becb7c0ceecf26b0dae2c6db80f9f2a8a6d4 broke the attachment of render buffers. This PR fixes the issue.
> Fix RenderBuffer not being attached

- examples/osgsimplegl3/osgsimplegl3.cpp
- src/osgViewer/GraphicsWindowCocoa.mm
This PR contains requested  parts of #92 previous PR concerning the osgsimplegl3 sample and the selection of the correct GL Profile when compiling with GL3 or Core Profile in GraphicsWindowCocoa.mm
> macOS CoreProfile

- include/osgDB/fstream
Only export the osgDB method implementations, instead of the entire
class, and hence avoid exporting symbols from the base class, which
then conflict with other compilation units when linking.
This avoids the need for /FORCE:MULTIPLE linker option with MSVC.
> Attempt to fix broken DLL exports from osgDB

- src/osgAnimation/RigTransformHardware.cpp
I don't remember exactly how I managed to get this to crash, maybe the shader source was loaded from cache or something like that.
> RigTransformHardware fix: warn; don't crash if MAX_MATRIX not found

- src/osg/TextureBuffer.cpp
- src/osgVolume/Property.cpp
from a synthetic test program I found that calling clone() on a new osgVolume::Scalarproperty and osg::TextureBuffer caused a crash. These functions are probably never used, but I think it would be better if the bug is fixed anyway.
> Submissions2c

- CMakeLists.txt
Hi Robert,
I failed to see the g++ -Wextra warnings because my cmake (version 2.8.9) is to old for the current script. Here is an enhanced version with support for a few more cmake version, and added warning flags for g++ 4.7 and 4.8 (-Wmaybe-uninitialized -Wextra).
I left -Wshadow out because my 4.7 compiler (4.7.2 ) generates a huge number of shadow warnings.
For g++ 6 and above I added -Wno-misleading-indentation ; I checked all warning g++ 6.1 generated and currently they don't indicate actual bugs.
> Visual Studio 2015: disable C4589: Constructor of abstract class X ignores initializer for virtual base class Y

- src/osg/VertexArrayState.cpp
Hi,
I think, one variable has not been renamed correctly.
> Missed rename in VertexAttribArrayDispatch

- include/osg/VertexArrayState
There is an implicit cast to GLint in the getter which I guess is not intentional.
> VAO id is a GLuint

- CMakeModules/FindCOLLADA.cmake
Hi Robert,
I managed to get collada  (collada_dom-2.3.1-src.tgz) to work with vc14 and boost 1.58, (collada_dom-2.3.1-src.tgz). I used this boost version because openVRML (openvrml-0.18.9.tar.gz) would not compile with boost 1.60
In order to build the osg collada plugin I need to add the updates in this PR.
> added vc14 (Visual Studio 2015) and boost 1.58 support in FindCOLLADA.cmake

- src/osgUtil/SmoothingVisitor.cpp
after duplicating the vertices to allow for multiple normals the indices of the new mesh (with duplicated vertices) were used with the vertices of the old mesh, causing a vector subscript out of range error.
> fix bug in SmoothingVisitor tripped by bunny.ply

- .codedocs
- README.md
This PR adds a configuration file for [CodeDocs.xyz](https://codedocs.xyz/) a GitHub integration that generates and hosts Doxygen documentation (Disclosure, I am one of the CodeDocs creators, and longtime OpenSceneGraph user). Like Travis-CI it will regenerate after each update to the repo.
I have this working on my fork of OpenSceneGraph now, and you can see the results [here](https://codedocs.xyz/CodeDocs/OpenSceneGraph/). The PR also adds a badge to the README.md, which you can see an example of, again, in my [fork](https://github.com/CodeDocs/OpenSceneGraph/).
Finally, for this to work, someone with access to the 'openscenegraph' GitHub account will have to login to CodeDocs and enable OpenSceneGraph.
I hope this is useful, I think it is a nice way to have always updated Doxygen …
> Use CodeDocs for Doxygen documentation

- src/OpenThreads/win32/Win32Thread.cpp
Hi Robert,
the current windows implementation uses a 32 bit affinity and a 32 bit shift - constraining the mask to only 32 cpu's. Documentation says 64 bit windows can use 64 cpus in a processor group - sadly I don't have a machine to test this on.
> unlock cpu's 32-63 on 64 bit windows

- src/osg/StateSet.cpp
Fix a typo in StateSet::compileGLObjects that caused compilation of attributes to not be executed unless checkForGLErrors is true.
Regression introduced with commit 99cb8ebacf2485ccb704c66865ab09a2e7190256
> Fix flow control issue in StateSet::compileGLObjects

- src/osgPlugins/iges/ReaderWriterIGES.cpp
- src/osgPlugins/iges/ReaderWriterIGES.h
* Remove unneeded XSDRAW.hxx header inclusion.
* Define WNT only on windows, because it is used for choosing between
win threads or pthreads.
> Several tweaks for compiling OpenCascade plugin:

- src/OpenThreads/pthreads/PThread.cpp
I also replaced all printf's currently in this source file with OSGNOTIFY to get this more
in-line with the rest of OSG.  Its possible these could just be removed I suppose but
not being the author it would probably be best to just let everyone else comment on
this subject before just removing them.  Setting it to OSGNOTIFY should at least keep
them from outputting unwanted messages for now.
> Fixed compile time errors that occur when you have ALLOW_PRIORITY_SCHEDULING defined

- src/osgPlugins/obj/OBJWriterNodeVisitor.h
- src/osgPlugins/obj/ReaderWriterOBJ.cpp
Two improvements for the OBJ writer plugin are provided. The first allows support for a StateSet to be present in an `osg::Group` rather than directly associated to a node when converting to OBJ. It solves an issue where an empty `.mtl` file is generated. The second allows user to specify a precision when writing an OBJ file, rather than the default 6 digits. It also defaults to double max precision.
> Improvements for the OBJ writer plugin

- src/osgViewer/StatsHandler.cpp
add visual info to the stats showing the current binary is a DEBUG version.
> DEBUG FPS counter in red and named "DEBUG Frame Rate:"

- src/osgViewer/StatsHandler.cpp
a tiny change I made while working on affinity and threads: a minimum size for the stat bar top with, to make even very small bars visible.
> improve stats display

- src/osgUtil/Statistics.cpp
While optimizing some old files I found it usefull to have the optimizer print out some info about dynamic drawables, transparent renderbins and other renderbins. 
> added some info about dynamic drawables and transparent bin to Statistics

- src/osgDB/InputStream.cpp
I've added some info when readImage() fails to load a file, following the style of the other error messages.
Previously the code was just printing "File not found", without mentioning which function generated the error and which file failed to load, which wasn't informative.
> Additional info when fail to load images

- src/osgTerrain/GeometryTechnique.cpp
- src/osgViewer/DarwinUtils.mm
The partial derivative for the x-coordinate has been wrongly calculated: only a single sided derivative was calculated.
> BUG FIX - Wrong calculation of terrain normals in GeometryTechnique

- include/osgUtil/Optimizer
- src/osgUtil/Optimizer.cpp
Several optimizers were not functioning correctly when used with new-style scene graphs where Drawables are placed directly in the scene graph rather than under a Geode.
The changed version was tested successfully on a few different models.
Still broken are:
FlattenStaticTransformsDuplicatingSharedSubgraphsVisitor
MergeGeometryVisitor
> Optimizer fixes

- src/osg/GLExtensions.cpp
Hi Robert,
I have made some inprovements to src/osg/GLExtensions.cpp:
Check extensions trough extermination string - not by function pointer value.
Added a few validContext tests to ensure no functions or isExterntionSupported bool is set for an non valid context.
Remove duplicates / merge some lines.
Removed "GL_APPLE_texture_2D_limited_npot" from isNonPowerOfTwoTextureMipMappedSupported.
> GLExtensions.cpp: Fixed a few typo's in old function names.

- src/osg/State.cpp
The GLExtension object is now reused instead of creating a new when allocating a state on the same ContextID. The static map that stores the GLExtensions is only reset when all references to the extension object are released.
> Bug fix to not crash when using shared context and adding / removing windowed views dynamically

- src/osg/State.cpp
I decided to backport the fix for this issue which caused OSG to redundantly glUseProgram() before every single draw call.
For me the difference in FPS is rather significant:
Before:
Draw 7.7ms
After:
Draw 5.0ms
> Backport State fix to 3.4 branch

- examples/CMakeLists.txt
- examples/osgbindlesstext/CMakeLists.txt
- examples/osgbindlesstext/osgbindlesstext.cpp
- include/osg/Array
- include/osg/GLDefines
- include/osg/GLExtensions
- include/osg/Uniform
- include/osgDB/DataTypes
- include/osgDB/OutputStream
- include/osgDB/StreamOperator
- src/osg/GLExtensions.cpp
- src/osg/State.cpp
- src/osg/Uniform.cpp
- src/osgDB/ClassInterface.cpp
- src/osgPlugins/ive/DataOutputStream.cpp
- src/osgPlugins/ive/DataOutputStream.h
- src/osgPlugins/ive/DataTypeSize.h
- src/osgPlugins/osg/AsciiStreamOperator.h
- src/osgPlugins/osg/BinaryStreamOperator.h
- src/osgPlugins/osg/XmlStreamOperator.h
- src/osgWrappers/deprecated-dotosg/osg/Geometry.cpp
This adds support for 64 bit integers as a data types (UInt64Array + Int64Array) for a large number of classes. 64 bit int extension was added to OpenGL to add support for bindless textures among other things. The extensions for the bindless textures as well as 64 bit uniforms were added as part of this.
The example osgbindlesstext was utilizes some of this, as well as gives a limited example on how to use bindless textures + instancing.
> Added support for unsigned 64 bit ints + some code for bindless textures

- src/osgWrappers/serializers/osgParticle/Particle.cpp
read endbracket for fileversion 145:
osgconv spaceship.osgt spaceship2.osgt; osgconv spaceship2.osgt spaceship3.osgt; osgviewer spaceship3.osgt 
shows the partice engines have stopped working, due to the missing read of an endbracket in file version 145 and up.
> Submit serializer particle

- src/osgWrappers/serializers/osgParticle/Particle.cpp
causing the datavariance in  osgParticle-SizeInterpolator and -ColorInterpolator to disappear.
> fix bug in osgb/osgt/osgx readerwriter osgParticle

- src/osgDB/InputStream.cpp
Hi Robert,
I found a bug crashing the osg when reading an osgt file with a missing texture being reference a secont time by UniqueID. A minimal example of an osgt file is attached (as .zip).
[MISSING_TEXTURE.zip](https://github.com/openscenegraph/OpenSceneGraph/files/905693/MISSING_TEXTURE.zip)
> fix a crash when reading an osgt file with multiple references to a missing texture.

- README.md
- src/osgPlugins/imageio/ReaderWriterImageIO.cpp
- src/osgViewer/GraphicsWindowCocoa.mm
This commit fixes macOS clang compiler warnings regarding use of logical AND vs bitwise AND.
Minor code whitespace/formatting issues.
> Fixes compiler warning regarding logic vs bitwise AND

- examples/osggeometry/osggeometry.cpp
Long-time lurker, first-time contributor.  This is fairly minor, but I noticed that the image and the points in examples/osggeometry are very hard to see if you view them close to edge-on.  This PR turns off lighting for both of those geodes so they are equally visible at any angle.  I hope this helps!  Please let me know if you have any questions or comments.  Thanks!
> Turned off lighting in examples/osggeometry

- src/osgDB/DatabasePager.cpp
This solves a bug with some shared library configurations. Sometimes the DatabasePager Singleton is initialised before one can call other configuration options like "setNumOfDatabaseThreadsHint". But OSG initialise it here:
https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgDB/DatabasePager.cpp#L1555 
So this call in the constructor is not needed.
> Avoid call of SetupThreads in DatabasePager Constructor 

- CMakeLists.txt
Modern iPhone simulators (at least as of Xcode 8.2) require both i386 and x86_64 binaries.
This tiny change makes sure OpenSceneGraph is built for both platforms when building for iPhone simulator.
> Add x86_64 architecture to iOS simulator

- doc/Doxyfiles/doxyfile.cmake
I saw from the forum ([example](http://forum.openscenegraph.org/viewtopic.php?t=15435)) that osgUI has some advantages over osgWidget.  However, when I went looking in the Doxygen output, I didn't see osgUI.  This PR just causes Doxygen to make osgUI docs :) .  I also put the doxyfile input directories in alphabetical order so I could more easily make sure I had them all.
I see there are already some doc comments in osgUI, so I think this is in keeping with your intention.  I checked the issues and pull requests (open and closed), Google search results, and the list of branches, and I don't see anything suggesting osgUI is being left out on purpose.  If it is, my apologies for missing that fact!
> Added osgUI to Doxygen-generated documentation

- include/osg/Array
- src/osg/Array.cpp
`Array::className()` had fallen out of date with respect to Array::Type (at commit 3d2f4ea4040bc14f94f40b7ef430e69d050cfb0c).  This commit updates `className()`, and adds documentation and a debug message to serve as a reminder for future additions of values to Array::Type.
I used `///` Doxygen comments rather than `/** */` because @filnet said in his review of #250 that he also preferred avoiding `/* */` comments.  Happy to change them if you like!
> Make Array::className() support all Array::Type values

- src/osgViewer/StatsHandler.cpp
change static_cast to dynamic_cast to avoid type cast error
> fix StatsHandler crush on windows

- include/osg/State
- src/osg/State.cpp
Hello, Robert!
This PR is for the OpenSceneGraph-3.4 branch, but maybe can be used for master.
There was a commit ad0a73273c972fe07e5b3f71c1d144e80b0976ed which fixed "the State::DefineMap::changed flag is not resetted to false after currentDefines are updated", but this flag is not correctly changed in push/popDefileList functions.
For example:
Group* parent = new Group;
parent->getOrCreateStateSet->setDefine("LIGHT", StateAttribute::OFF)
Node* node1 = new Node;
node1->getOrCreateStateSet->setDefine("LIGHT", StateAttribute::**ON**)
Node* node2 = new Node;
parent->addChild(node2);
Without this patch, node2 will be with "**LIGHT ON**", but must be without light
std::pairs must be compared, not just their keys.
PS
I have the same problem in 3.5.6 dev release and talked about this while …
> pragma(tic) shader composing fixes in the State

- include/osg/GLDefines
- src/osgPlugins/imageio/ReaderWriterImageIO.cpp
Hello, Robert!
In this PR there are changes for imageio plugin for Apple macOS and iOS.
Newer plugin can open 8, 16, 24, 32 bit images with 1, 2, 3 and 4 components + it can be faster (no benchmarking :^/ ) and is better for OpenGL 3.2 (core profile) and GLES2/3
Tested on iOS 7.1 (GLES3/GLES2) and upper, on macOS 10.12 (GL3 in compatibility mode)
Also I have some build problems with GLDefines on macOS (GL3 + GL2 profile) - patch attached
"GL3 + GL2" because OpenSceneGraph 3.4 version works only in compatibility profile mode (no VAO)
OSG 3.5.6 has VAO, so there we can switch to core profile
This patch can also be merged with master.
KOS
> IMAGEIO plugin tweak

- include/osgAnimation/UpdateUniform
- src/osgDB/OutputStream.cpp
- src/osgWrappers/serializers/osgAnimation/LibraryWrapper.cpp
- src/osgWrappers/serializers/osgAnimation/UpdateVec2fUniform.cpp
- src/osgWrappers/serializers/osgAnimation/UpdateVec4fUniform.cpp
Hello, Robert!
This patches are **already in the master**.
Should not break any compatibility with 3.4.0.
KOS
> osgAnimation: classes UpdateVec2fUniform and UpdateVec4fUniform added

- include/osg/PrimitiveSetIndirect
- src/osgUtil/DrawElementTypeSimplifier.cpp
*add resize methods method in  IndirectCommandArrays (it allows user to work without casting to the concrete class result of MDI.get IndirectCommandArray())
*move getTotalDataSize in  IndirectCommandArrays interfaces
*comply with other DrawElementsXXX removing parameters in mdi constructors and add several method ( allow use of osgUtil::DrawElementTypeSimplifer on these)
*MDI support in osgUtil::DrawElementTypeSimplifer
> add resize methods method in IndirectCommandArrays ..etc..

- src/osg/GLExtensions.cpp
A little bit better realization of Emscripten in GLExtensions.cpp, that does not depends on SDL2 module.
PS
SDL_GL_GetProcAddress realized via eglGetProcAddress
> Emscripten: EGL instead of SDL2 in GLExtensions.cpp

- src/osgPlugins/dae/daeWTransforms.cpp
Note that although the value_type is currently always double, using the proper typedef will open the door to implementing a float Quaternion in the future (as I have actually done so in my own fork).
I can open a PR for the float quaternion too, if we want such a thing? I used it for a performance improvement in my animation code. It is implemented as a build time option similar to the float matrix option.
> Use osg::Quat::value_type instead of double in collada plugin

- src/osg/Geometry.cpp
GL_QUADS are deprecated in GL3, so they are changed to GL_TRIANGLES. 
There were two options for fix this bug:
**1)**  change line
**#if defined(OSG_GLES1_AVAILABLE) || defined(OSG_GLES2_AVAILABLE)** 
to
**#if defined(OSG_GLES1_AVAILABLE) || defined(OSG_GLES2_AVAILABLE) || defined(OSG_GL3_AVAILABLE)**
**2)** Delete GL_QUADS (Like it was made in StatsHandler) and use GL_TRIANGLES no matter of platform.
Opt 2 is in the PR
KOS
> [*] createTexturedQuadGeometry: fixed for GL3 spec

- src/osg/Texture.cpp
Hi Robert, I actually have no idea if porting this is correct or what the 'change in search direction' in the earlier commit was (couldn't find that commit). However, since this change appears to have [fixed](https://bugs.openmw.org/issues/3904) an issue with texture mipmaps appearing black in OpenMW on certain systems, I figured to just propose this and rely on your neverending wisdom to see if it's OK. Probably too late for 3.4.1 now but maybe there'll be a 3.4.2? Thanks!
> Applied sizedInternalFormats change to 3.4 branch

- src/osgPlugins/vnc/ReaderWriterVNC.cpp
Just commented out the unused variables.
> ReaderWriterVNC.cpp fix g++ warnings

- src/osg/Geometry.cpp
Hello, Robert!
This PR will fix compileGLObjects function in osg::Geometry while using VAO.
**extensions->glBindBuffer(GL_ARRAY_BUFFER_ARB,0);
extensions->glBindBuffer(GL_ELEMENT_ARRAY_BUFFER_ARB,0);**
should be called after "VAO compilation part"... I think
KOS
> Geometry::compileGLObjects function VAO fix

- src/osgDB/FileUtils.cpp
Such a #define already exists for other platforms.
Android NDK 14 worked fine without the #define, but something was changed in NDK 15. Now OSG only builds for Android using this #define.
More details are available at OSG guide issue: https://github.com/OGStudio/openscenegraph-cross-platform-guide/issues/2
> Fix stat64 build issue with NDK 15 by definining it as stat for Android

- src/osg/Notify.cpp
… (causing multitreading issues) by pre-allocating 4095 bytes.
While digging into treading problems I found out that Visual Studio's ostream has a problem if thread A starts some output to the stream, thread B writes enough output to cause the buffer to be resized and thread A then continues to write to the old buffer, while only respecting the length of the new buffer - overrunning the now released old buffer and overwriting other (valid) data. pre-allocating a reasonable buffer helps to minimize the problem - in my case it disappeared.
> reduce the need to reallocate the std::ostream buffer behind osg::Notify

- examples/osgSSBO/osgSSBO.cpp
- examples/osgatomiccounter/osgatomiccounter.cpp
- examples/osgbindlesstext/osgbindlesstext.cpp
- examples/osggpucull/osggpucull.cpp
- examples/osguniformbuffer/osguniformbuffer.cpp
- include/osg/BufferIndexBinding
- include/osg/Matrixd
- include/osg/Matrixf
- src/osg/BufferIndexBinding.cpp
- src/osg/Matrix_implementation.cpp
- src/osgWrappers/serializers/osg/BufferIndexBinding.cpp
1) change the design of BufferIndexBinding to work with BufferData instead of BufferObject: it's more consistent with the rest of osg, allow user to bind bufferdata relative stuff, and further it allow serialization
2) add 2 methods: transpose (4x4 transpose) and transpose3x3 (orthogonal part of a mat4x4)
> change the design of BufferIndexBinding to work with BufferData instead of BufferObject +matrix transpose

- src/osgPlugins/tga/ReaderWriterTGA.cpp
Hi Robert,
The pr:
Add support for type-1 (colour-mapped, uncompressed) targa images to … #306 by "AnyOldName3"
cause a few compiler warnings both by gcc and Visual Studio:
/home/travis/build/openscenegraph/OpenSceneGraph/src/osgPlugins/tga/ReaderWriterTGA.cpp: In function ‘unsigned char* simage_tga_load(std::istream&, int*, int*, int*)’:
/home/travis/build/openscenegraph/OpenSceneGraph/src/osgPlugins/tga/ReaderWriterTGA.cpp:366:75: warning: ‘indexsize’ may be used uninitialized in this function [-Wmaybe-uninitialized]
convert_data(colormap, formattedMap, i, indexsize, format);
^
/home/travis/build/openscenegraph/OpenSceneGraph/src/osgPlugins/tga/ReaderWriterTGA.cpp:364:13: warning: ‘colormapLen’ may be used uninitialized in this function [-Wmaybe-uninitialized]
for (int i = 0; i < …
> fix gcc/VC compile warnings, reject color mapped tga files with missing colormap.

- include/osg/Group
[Checking for duplicates](https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/Group.cpp#L77) is only done if ENSURE_CHILD_IS_UNIQUE is defined, but this is never defined anywhere.
> Fix docs for Group::addChild to match implementation

- examples/osgemscripten/CMakeLists.txt
Without the fix there are the following errors with `osgemscripten` example:
* OSG_WINDOWING_SYSTEM is incorrectly detected as X11, which doesn't compile under Emscripten
* CMake configuration error prevents the first configuration round, so one has to reconfigure to suppress the error
This fix removes both problems.
> Fix Emscripten build errors

- src/osg/Program.cpp
I ran into an issue where osg::Program::isFixedFunction() was called with openGL CoreProfile used and without fixed function available. I believe that this method shouldn't return true if fixed function is unavailable, even if _shaderList.empty() is true.
> osg::Program::isFixedFunction() should'nt return true if fixed function unavailable

- src/osg/Program.cpp
Under macOS the glValidateProgram reports too many false negatives (errors) about missing buffers, etc..
From the internet https://stackoverflow.com/questions/15335510/opengl-glvalidateprogram-error-on-mac-os-x :
« […] The purpose of glValidateProgram is not to use it as an added "check" step after linking the program, because the GL and application state is hardly ready for actually using that program at this point, probably it's even before we get around to initializing the default framebuffer (its bitdepth, its multisample buffers, etc), and that's what the error hints at.
An appropriate place to call glValidateProgram would be right before you make a real render call. »
> Under macOS the glValidateProgram reports too many errors 

- src/osgUtil/LineSegmentIntersector.cpp
For some reason the LineSegmentIntersector was checking this flag when testing bounding spheres, but not for bounding boxes. This inconsistency has been fixed to check the flag in both cases, just like the cull visitor does.
> LineSegmentIntersector: respect the 'cullingActive' flag for bounding box check

- src/osgPlugins/vnc/ReaderWriterVNC.cpp
when using a different port like localhost:5901.vnc the password needed to be set with "--login localhost:5901 unusedUsername password".
with this change the password for localhost is used if no password for localhost:5901 is found.
> VNC: try to find password for host if no password for host:port is found

- src/osgPlugins/png/ReaderWriterPNG.cpp
When a 16bit PNG image is loaded, the internalTextureFormat is set to unsized (i.e pixelFormat) constant. This results in 8 Bit Texture2D, which is not expected.
> Fix loading of 16bit PNG images

- include/osgAnimation/RigTransformSoftware
- src/osgAnimation/RigTransformSoftware.cpp
not sure if this bug  affects master too ...
if a bone is not found in the bone map it's removed but vertexggroup is not normalized after that
> fix normalization bug (happen too early )

- src/osg/Image.cpp
- src/osg/dxtctool.cpp
- src/osg/dxtctool.h
-added dxtc support in Image::getColor:
now the patent has expired we can decode the color of a pixel.
-enhanced Image::isImageTranscent to test opacity of dxt3 and dxt5 images:
scan pixel alpha values to see if any of them has some transparency
-added function to strip the alpha from dxt3 and dxt5 blocks, converting them to a dxt1 block,\
-added function to rotate/flip dxt 1/3/5 blocks
> added dxtc support in Image::getColor, Image::isImageTranscent testdxt3 and dxt5

- include/osg/Image
- src/osg/Image.cpp
-added support for variable block compression sizes
-added types introduced with GL_KHR_texture_compression_astc_hdr extention
-added copySubImage support to copy compressed blocks (aligned with block footprint only)
-check added to copy to give a warning instead of a crash if new failed
-guard added to Image::getColor to return (1,1,1,1) for unsupported compressed textures (=not dxtc)
TODO/MISSING
-Image::flipHorizontal no guard/support for any compression
-Image::flipVertical() very crude OSG_NOTICE for compressed textures, only POT dxt textures will actually be flipped
> copySubImage support for block compressed images, added support for astc compressed type.

- .travis.yml
I noticed that the build jobs in travis time-out quite often. I say that the travis file has some configuration to use ccache but it was not working. Hopefully with these changes the build jobs will run faster and complete more often. There is some information on how the cache is kept between builds and pull requests in https://docs.travis-ci.com/user/caching/#Pull-request-builds-and-caches.
These screenshots show the time difference when the cache is empty and when it contains all the object files that are being generated.
Cold cache:
Hot cache:
> Fix ccache on travis

- include/osgDB/DataTypes
- include/osgUtil/RenderLeaf
- src/osgViewer/GraphicsWindowCarbon.cpp
- src/osgViewer/GraphicsWindowCocoa.mm
if protocol is not defined a compiler warning is raised with respect to line 1726:
`        [NSApp setDelegate: [[CocoaAppDelegate alloc] init] ];
`
> Removal of compiler warning for Cocoa builds

- src/osgText/Glyph.cpp
Hi Robert,
std::max trips my VC2015 compile:
E:\osg\35\laurens\OpenSceneGraph\src\osgText\Glyph.cpp(91): error C2039: 'max': is not a member of 'std'
> use osg::maximum, not std::max

- src/osg/Texture.cpp
According https://www.khronos.org/opengl/wiki/Common_Mistakes#Creating_a_complete_texture final sentence:
mipmaps should be upload with glTexImage2D and not glTexSubImage2D
perhaps _borderWidth should be replace by 0...don't know
>     following guidance from OpenGL Common Mistakes:

- src/osgPlugins/logo/ReaderWriterLOGO.cpp
Logos were culled when the center of the scene bounding sphere was culled.
This PR corrects this on master
> Make the culling be disabled at the drawable level 

- src/osgPlugins/logo/ReaderWriterLOGO.cpp
Logos were culled when the center of the scene bounding sphere was culled.
This PR corrects this
> Make the culling be disabled at the drawable level

- src/osgUtil/MeshOptimizers.cpp
When an array is shared within and outside a geometry, it's still worth it and safe
to recreate the reference within each individual geometry.
> Improve SharedArrayOptimizer

- src/osg/VertexArrayState.cpp
I developp an InterleavedGeometry overriding drawverteximpl in order to manage myself vbo I bound before calling manual form of Dispatcher::setArray and come into several problems
- as no array is provided, we should assume user already have bound its custom vbo
- a test an ptr is not fitted as offset in a bo can be 0 so i removed it
I don't know it this particular use if vas modifiedcount should be modified but i let it as it was
> add a fix in order setArray  work with an user managed interleaved array

- src/osgPlugins/dae/ReaderWriterDAE.cpp
Fix a bug when colladom 1.4 and 1.5 are both available.
As currently OSG DAE plugin is only compatible with colladom 1.4.1, we must explicitly use the version 1.4.1 by setting the correct third argument of the DAE constructor.
> [Fix] Use explicitelly colladom 1.4.1

- CMakeLists.txt
I have made this auto-detection optional (default ON).
> Detecting the windows version at build time breaks cross-compilation.

- src/osgPlugins/fbx/WriterNodeVisitor.cpp
- src/osgPlugins/fbx/WriterNodeVisitor.h
Refactored the internal routines in the WriterNodeVisitor that were taking a Geode as argument to use a list of geometries. 
This way both Geodes containing multiple geometries or single geometries attached as nodes to the scene graph can serialize themselves using such routines.
> Fbx writer: added support to convert geometries directly attached as node

- include/osg/ImageTexture
- include/osg/StateAttribute
- src/osg/CMakeLists.txt
- src/osg/ImageTexture.cpp
allow differents IUBs for a single Texture
(perhaps naming should be changed)
todo if accepted: feature has already been tested but the old impl must be removed)
> add flexier Image Unit Binding implementation 

- examples/osgcomputeshaders/osgcomputeshaders.cpp
- examples/osggpucull/osggpucull.cpp
- include/osg/BindImageTexture
- include/osg/Texture
- src/osg/Texture.cpp
- src/osg/TextureBuffer.cpp
- src/osgWrappers/serializers/osg/BindImageTexture.cpp
- src/osgWrappers/serializers/osg/Texture.cpp
- add a serializer
- remove old stuff
- adapt example
Just an observation: Perhaps merging BindImageTexture files with BufferIndexBinding ones could resulting in faster build..
> complete Imagebinding integration 

- src/osgViewer/ViewerBase.cpp
I was wonder why heavy multithreaded osgViewer::Viewer - based programs works well when running with ENV. variable
**OSG_THREADING=DrawThreadPerContext osgviewer-based-program** (osgviewer etc.) 60 FPS
and works bad (10FPS with lags etc.) when running (with arguments) like
**osgviewer-based-program --DrawThreadPerContext**
The reason was that osgViewer::ViewerBase setThreadingModel function starts threading by calling setUpThreading. I think it should not, it should only change threading model. Of course, it must restart if Viewer already threading.
Maybe there is also another issue associated with affinity when threading model changed dynamically.
The reason of using **needSetUpThreading** additional flag is that function setUpThreading is virtual and can possibly use _threadingModel …
> osgViewer::ViewerBase setThreadingModel function fixed

- include/osgWidget/Util
Hi Robert,
vs 2017 gives me a rather large compiler warning:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\algorithm(911): warning C4244: '=': conversion from 'int' to 'char', possible loss of data (compiling source file E:\osg\35\laurens\OpenSceneGraph\src\osgWidget\Window.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\algorithm(924): note: see reference to function template instantiation '_OutIt std::_Transform_no_deprecate<_InIt,_OutIt,int(__cdecl *)(int)>(_InIt,_InIt,_OutIt,_Fn &)' being compiled
with
[
_OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
_InIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
_Fn=int (__cdecl *)(int)
] …
> fix vc2017 compile warning 'unsigned int' to 'const char'

- src/osgAnimation/RigTransformHardware.cpp
Hi Robert,
chasing vs 2017 compiler warning
C4189: 'maxBonePerVertex': local variable is initialized but not referenced
Variable can simply be removed.
Laurens.
> remove unused variable "maxBonePerVertex"

- examples/osganalysis/osganalysis.cpp
Hi Robert,
chasing vs 2017 compiler warning
OpenSceneGraph\examples\osganalysis\osganalysis.cpp(259): warning C4458: declaration of 'ArrayVector' hides class member
I found the local typedef and the variable unused. Seems to me those can be removed.
Laurens.
> remove unused variable "newArrays"

- examples/osgdirectinput/DirectInputRegistry.cpp
Hi Robert,
a compiler warning from vs2017 pointed me to a bug in examples\osgdirectinput
As I have no joystick I can't test any of the code, but here's a fix anyway.
> fix bug: potentially uninitialized local variable 'hr' used

- src/osgWidget/Input.cpp
Hi Robert,
a compiler warning from vs2017 (C4244: 'argument': conversion from 'unsigned int') pointed me to a bug in the osgWidget::Input copy to clipboard code; the osgText is a vector of uints representing (UTF32? - not sure) characters and should not be truncated into a char type.
> text copy - get unicode text to clipboard.

- src/osg/os_utils.cpp
see https://github.com/openscenegraph/OpenSceneGraph/issues/458
> os_utils: fix non portable use of "defined"

- src/osg/GLExtensions.cpp
On Android it's possible to have `libGL.so` with the gl4es wrapper: https://github.com/ptitSeb/gl4es which translates GL1 calls into GLESv1/GLESv2
This pull request fixes compilation error when OSG is built with `OSG_GL1_AVAILABLE` for Android.
(This is useful for porting projects that use OSG but also depend on the underlying OpenGL implementation, e.g. openmw)
> getGLExtensionFuncPtr: support gl4es wrapper on Android.

- include/osg/ValueObject
bugfix: 
-GetScalarValue returns inverted values for booleans
-SetScalarValue needs to be a SetValueVisitor
Hi Robert,
I saw a very strange line in the code you added last December, and while trying to test I found a second. I don't think this code gets used anywhere, but that makes it a lot simpler to fix it now.
test code: (after changing SetScalarValue to inherit from SetValueVisitor
{
OSG_NOTICE << "test bool" << std::endl;
bool test = true;
osg::TemplateValueObject<bool> *obj = new osg::TemplateValueObject<bool>("test", test);
obj->getScalarValue(test);
OSG_NOTICE << "test is supposed to be true; value:" << test << std::endl;
obj->setScalarValue(test);
obj->getScalarValue(test);
OSG_NOTICE << "test set/get; value:" << test << std::endl;
test = true; …
> bugfix: GetScalarValue returns inverted values for booleans

- src/osgPlugins/lua/CMakeLists.txt
There is no problem, structure gets padded to keep alignment for 64 bit pointers.
> silence MSVC warning C4324: 'lua_longjmp': structure was padded

- include/osg/ClusterCullingCallback
- src/osg/ClusterCullingCallback.cpp
The radius parameter is already present in ClusterCullingCallback's set method but has been forgotten in the constructor.
The change is backwards compatible.
> Addition of radius parameter for ClusterCullingCallback's constructor

- src/osgPlugins/Inventor/DeprecatedGeometry.h
Hi Robert,
I compiled the coin library for windows, and found that the Inventor plugin in the 3.5.x tree doesn't compile on windows, due to a wrong __declspec(dllimport) modifier. This was introduced when the code was moved into the plugin (and removed from the main osg.dll) on 4 september 2016 - apparently it's not compiled on windows very often.
> Remove OSG_EXPORT from deprecated_osg::Geometry in inventor plugin.

- src/osg/GLExtensions.cpp
- src/osg/Image.cpp
and GL_TEXTURE_BINDI…NG_2D_ARRAY_EXT
to fix a compile error on windows.
> remove _EXT from GL_MAX_ARRAY_TEXTURE_LAYERS_EXT 

- src/osgDB/Registry.cpp
"Unable to load ..." was printed if the library could be loaded, and it wasn't if not.
This incorrect, inverted logic was probably a copy-paste error.
> osgDB: Fix handling of return value of loadLibrary in Registry.

- include/osgDB/OutputStream
- src/osgDB/OutputStream.cpp
when write binary file, like osgb file, users can set plugin string data, such as "TargetFileVersion=80", to options object, then the features of output file will be limitted to so version 80.
> write binary file with a specific so version

- include/osg/GLExtensions
In most systems today sizeof(size_t) is larger than sizeof(GLsizei). Therefore, the inclusion of GLExtensions may introduce a lot of compiler warnings as array.size() (of type size_t) is passed to a function with a parameter of type GLsizei.
> Removal of compiler warnings caused by integer conversions

- src/osgDB/OutputStream.cpp
When writing images, OutputStream can search files using its Options object rather than always using FilePathList object of global Registry instance.
>  OutputStream writes images using its Options object

- src/osgViewer/GraphicsWindowIOS.mm
fixes the compile error when targeting gles3 only
> missing gles2 check

- src/osgPlugins/obj/obj.cpp
Parsing key 'map_bump' was processed in the block, where the attributes
for 'bump' are extracted and results into having parts of the key in the
extracted filename, generating an invalid filename.
The mentioned string compare could be removed without loosing any features,
because the key 'map_bump' is parsed correctly some lines below.
> Remove duplicated and incorrect fetching of 'map_bump' attributes in obj plugin

- src/osgViewer/GraphicsWindowWin32.cpp
compilation error was introduced by msvc specific change
see https://github.com/openscenegraph/OpenSceneGraph/commit/bb169979a1054e2fa63a7ea82c9c8bec87e90494
> mingw: fix compile error in GraphicsWindowWin32.cpp

- include/osgManipulator/TrackballDragger
Hi Robert!
Just a small change to fix the osgManipulator build.  TrackballDragger needs <osg/Geode> included since IntersectVisitor was removed.
Thanks!
Jason
> Including osg/Geode to fix osgManipulator build

- include/osg/Uniform
Hey Robert,
This PR removes the unimplemented Uniform::getNameID from Uniform header as it's defined in UniformBase now.  This fixes a linker error in osgEarth when against the master.
Jason
> Removed unimplemented Uniform::getNameID from Uniform header

- include/osgManipulator/TrackballDragger
Getting a build failure on MSVC 2015 due to missing Geode include in two of the trackball manipulators.  This fixes the build and seems like a reasonable place for it due to the ref_ptr<Geode> member variable.
> Fix includes for MSVC 2015 build.

- src/osg/DisplaySettings.cpp
- src/osg/GraphicsContext.cpp
Reverts openscenegraph/OpenSceneGraph#536
> Revert "When GL3 build is enabled, default context requested is version 3.3, …"

- include/osgParticle/ParticleSystem
The osgParticle::ParticleSystem header contained some functions which are no longer implemented due to refactoring the drawImplementation towards VBO.
> FIX: <osgParticle> removed unimplemented functions from header

- src/osgText/TextBase.cpp
In a large-coordinate environment (e.g. osgEarth) osgText with SCREEN_COORDS can exhibit jittering of the text. This patch performs the pixel size computation in double-precision to resolve this issue.
> osgText: perform pixel size computation in double-precision to prevent jitter

- doc/Doxyfiles/auto_Doxyfile
- doc/Doxyfiles/core_Doxyfile
- doc/Doxyfiles/doxyfile.cmake
Hi Robert,
just got doxygen working on my windows machine, an I got a few warnings:
1>------ Build started: Project: doc_openscenegraph, Configuration: Debug x64 ------
1>CUSTOMBUILD : warning : tag INPUT: input source `E:/osg/37/laurens/OpenSceneGraph/include/osgQt' does not exist
1>CUSTOMBUILD : warning : source E:/osg/37/laurens/OpenSceneGraph/include/osgQt is not a readable file or directory... skipping.
this PR gets rid of the warnings, and while I suspect only one of the doxyfiles is actually used in my configuration I guess it's better to update all three.
These changes are appropriate for the 3.6 tree too.
> remove include/osgQt from doxyfiles; add osgPresentation and osgUI

- examples/osgviewerMFC/MFC_OSG.cpp
The position of viewport doesn't setup properly, some part of viewer is out of CMFC_OSG_MDIView,  and not visible.
> Fixed the position of the viewport for the camera

- src/osgPlugins/ffmpeg/FFmpegClocks.cpp
- src/osgPlugins/ffmpeg/FFmpegDecoderVideo.cpp
playing .mp4 movie with audio will start to stutter in audio and video after about 10 seconds.
> resolve av sync failure with ffmpeg 3.2 and up

- src/osgPlugins/OpenFlight/expGeometryRecords.cpp
I'm about to send a mailing list post about this change and why it's needed.  In short, check out osg::Texture::getModeUsage().  Because it has `ifdef OSG_GL_FIXED_FUNCTION_AVAILABLE` around it, the `GL_TEXTURE_2D` mode never gets set `ON`, it's kept at `INHERIT`.  That means `isTextured()` always returned false.
> OpenFlight: Textures now correctly export in GLCORE mode.

- src/osgPlugins/osga/OSGA_Archive.cpp
Remove call to nonexistent member seekpos() of std::fpos in VS 2017 version 15.8. It has removed in our curent latest published release VS 15.8 preview 3(_MSC_VER=1915). So it failed with below issue：
error C2039: 'seekpos': is not a member of 'std::fpos<_Mbstatet>'
See http://eel.is/c++draft/fpos -- to get to an offset you can convert to int; now there is no seekpos member in VS15.8.
We have fixed this issue in vcpkg (Microsoft/vcpkg#3753).
The previous PR that we discussed here: https://github.com/openscenegraph/OpenSceneGraph/pull/567
I send the new one, please help approve. Thanks!
> Remove call to nonexistent member seekpos() of std::fpos in VS 15.8

- src/osgPlugins/OpenFlight/expGeometryRecords.cpp
Minor fix, as pointed out by @mp3butcher on https://github.com/openscenegraph/OpenSceneGraph/pull/568
Sorry for not noticing on first pass.  All my test cases only had texture unit 0 and I missed the typo.  Priority on this seems low, edge case of an edge case.
Includes minor update on code style to match the rest of the file.
> FLT: Fix texture unit typo and code style from PR 568.

- CMakeModules/FindCOLLADA.cmake
* Handle MSVC_VERSION versions > 1910
* Specify PATH_SUFFIXES rather than individual PATHS for FIND_PATH
> Fix FindCollada.cmake for vcpkg installs

- examples/osgviewerWX/osgviewerWX.cpp
- examples/osgviewerWX/osgviewerWX.h
Cherry-pick old PR of @Alexibu
Needed upgrade of WXWidgets. This PR make sample compatible with WXWidgets from version 3.0.1
I successfully tested it with wxWidgets 3.1
Pull request was closed
https://github.com/openscenegraph/OpenSceneGraph/pull/47
Thanks
> updated osgviewerWX to remove deprecated calls in wxWidgets 3.x

- include/osg/Matrixd
- include/osg/Matrixf
Using USE_DEPRECATED_API, you can not disable Matrix's get/set methods with cmake.
> Renamed USE_DEPRECATED_API to OSG_USE_DEPRECATED_API

- src/OpenThreads/pthreads/CMakeLists.txt
This fixes a compilation failure in OpenThreads on cygwin x64 on Win8.1 and Win10 with gcc 7.3.0.  This is the smallest, most targeted fix I can think of, since I didn't want to unintentionally introduce any regressions.
Problem: `pthread_{yield,getconcurrency,setconcurrency}` are not declared in `pthread.h` on cygwin with gcc 7.3.0 (latest as of writing) unless `_GNU_SOURCE` is defined.  However, cmake's [`CheckFunctionExists`](https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html) doesn't test for declarations, just for linkage.  Therefore, cmake detects those functions as existing, but then OpenThreads fails to compile because they are undeclared.
Solution implemented in this PR: on cygwin, just don't use the functions that are hidden when `_GNU_SOURCE` is not defined. …
> On cygwin, don't use pthread functions that require _GNU_SOURCE in OpenThreads

- include/osg/GraphicsContext
- src/osgViewer/GraphicsWindowWin32.cpp
- src/osgViewer/GraphicsWindowX11.cpp
Refactor so `src/osgViewer/GraphicsWindowWin32.cpp` doesn't duplicate code in `include/osg/GraphicsContext`.  New macro `REGISTER_WINDOWINGSYSTEMINTERFACE2` can accept `OSGVIEWER_EXPORT`, introduced into Win32 in May as part of 0bca415d5af4647da868888c1588b9617dbe3eb8.
Also fixes the Cygwin build problem identified in #588, and still present in master (e008784ab67be96e3e079aecfd2fc115b7b7885b).  Uses a neat and tidy macro, per Robert's feedback on #588.
Also tested and works with osgQt on my Cygwin setup (0bca415d5af4647da868888c1588b9617dbe3eb8 refers to osgQt, so I tried it out).
> Remove duplication of REGISTER_WINDOWINGSYSTEMINTERFACE code in GraphicsWindowWin32

- src/osg/Texture.cpp
It seams safe to do that as this code path only used when glTexStorage available
> Add valid sizedInternalFormats for glTexStorage path

- src/osg/Texture.cpp
Change GL_RGBA16F to  GL_RGBA16F_ARB to fix Windows build.
> Change GL_RGBA16F to  GL_RGBA16F_ARB to fix Windows Build

- include/osg/Shader
- src/osg/Shader.cpp
Hi Robert!
Here is a change to Shader that protects the _programSet with a mutex.  Crashes can occur if you reuse Shader objects between multiple Programs b/c the addProgramRef and removeProgramRef functions aren't thread safe.  The VirtualProgram framework in osgEarth can generate Programs as needed using shared Shader objects, so we would see crashes when running with multiple windows using CullThreadPerCameraDrawThreadPerContext mode.
I've attached a simple example that shows the issue, it just creates and destroys programs in background threads that share a global Shader object.
Thanks!
Jason
[sharedshader.txt](https://github.com/openscenegraph/OpenSceneGraph/files/2349377/sharedshader.txt)
> Protect the _programSet in Shader with a mutex.

- src/osg/Image.cpp
I think there is a typo in the initial check for not doing anything if the data provided matches the ones already present.
> Fix typo in the initial check of Image::scaleImage().

- src/osgDB/OutputStream.cpp
This corrects the use-case of converting osg binary files( to and from) that have inlined image files. 
The OutputStream assumed that the file is physically available from the disk. This correction mimics the reader of inlined image files to select a writer and write the osg::Image into a buffer that will then be inlined into the stream.
> Added saving of inline Images without having the physical image file.

- applications/osgconv/osgconv.cpp
- examples/osgautocapture/osgautocapture.cpp
- examples/osgautotransform/osgautotransform.cpp
- examples/osgcamera/osgcamera.cpp
- examples/osgcompositeviewer/osgcompositeviewer.cpp
- examples/osgdistortion/osgdistortion.cpp
- examples/osgfpdepth/osgfpdepth.cpp
- examples/osghangglide/osghangglide.cpp
- examples/osgmemorytest/osgmemorytest.cpp
- examples/osgmovie/osgmovie.cpp
- examples/osgmultiviewpaging/osgmultiviewpaging.cpp
- examples/osgoscdevice/osgoscdevice.cpp
- examples/osgscreencapture/osgscreencapture.cpp
- examples/osgsidebyside/osgsidebyside.cpp
- examples/osgsimplegl3/osgsimplegl3.cpp
- examples/osgslice/osgslice.cpp
- examples/osgtexturecompression/osgtexturecompression.cpp
- examples/osgwindows/osgwindows.cpp
(when DISPLAY not :0.0)
It will avoid a lot of complains related to the new Ubuntu (gnome3) default policy (DISPLAY=:1) 
so merging it on release branch can be good idea too
> fix examples context creation for X11

- include/osgText/Glyph
- src/osgText/Font.cpp
- src/osgText/Glyph.cpp
Patch to address a thread-safety issue when creating osgText objects from multiple threads simultaneously.
> osgText: fixed thread-safety issues in Glyph and Font

- src/osgText/TextBase.cpp
Hi Robert,
Test size responds to rotation in 3.6 and master tree while it did not do that in previous osg versions.
Attached in zip a small file demonstrating the problem, when the scene is rotated the text size changes.
[testmeasure.zip](https://github.com/openscenegraph/OpenSceneGraph/files/2361146/testmeasure.zip)
> fix scale problem for osgText with characterSizeMode SCREEN_COORDS and _position set.

- src/osgGA/GUIEventAdapter.cpp
- src/osgViewer/CompositeViewer.cpp
- src/osgViewer/View.cpp
- src/osgViewer/Viewer.cpp
- src/osgWidget/ViewerEventHandlers.cpp
1) InputRange in GUIEventAdapter is **segment** not  **half-open interval**
2) Wrong code example:
```
bool invert_y = event.getMouseYOrientation()==osgGA::GUIEventAdapter::Y_INCREASING_DOWNWARDS;
if (invert_y && gw->getTraits()) y = gw->getTraits()->height - y;
```
Let **gw->getTraits()->height = 1080** and **y = 0**
then y will be 1080, but it must be **1079**!
So `y = gw->getTraits()->height - 1 - y;` will be ok ;)
KOS
> 1px error in GUIEventAdapter, View, Viewer and CompositeViewer major fix

- src/osg/Texture.cpp
I was getting a black image when enabling hardware mipmap generation on cubemaps. I believe the problem is that the base Texture class is hard coding GL_TEXTURE_2D when enabling mipmap generation, instead of using the target type from the derived class.
> Fix hardware mipmap generation for cube maps

- src/osgPlugins/fbx/ReaderWriterFBX.cpp
- src/osgPlugins/fbx/fbxRMesh.cpp
- src/osgPlugins/fbx/fbxReader.h
Loading an fbx model multiple times or across separate runs can result in different skeleton bone hierarchies. The problem is with how the "resolveBindMatrices" function resolves new bones. The iteration order is dependent on osgAnimation::RigGeometry pointer values, which can differ across runs. I've refactored the BindMatrixMap so that it maps bones to a map of bind matrices and set of geometry. This ensures a consistent and minimum number of bones are created for each unique bind matrix.
> Fix for inconsistent FBX bone hierarchy

- src/osgPlugins/gif/ReaderWriterGIF.cpp
Setting the reference time greater than the duration of a gif would cause a crash. Also, the current reference time is not immediately updated when manually setting the reference time.
> Fix for GifImageStream::setReferenceTime

- src/osgDB/OutputStream.cpp
I've made a change to osgDB::OutputStream::writeArrayImplementation so that it writes the array data in a single write operation for binary files. This significantly speeds up writing out osgb files for large data sets (e.g. point clouds). osgDB::InputStream already performs a similar optimization when reading array data from binary files.
> osgDB::OutputStream write array optimization

- src/osgPlugins/dds/ReaderWriterDDS.cpp
The DDS loader was not applying the correct internal format for certain HDR images (e.g. float/half_float formats)
> Fix for HDR DDS images

- src/osgViewer/GraphicsWindowWin32.cpp
These patches are from [MXE project](https://mxe.cc/).
[Tested build](https://github.com/mxe/mxe/pull/2224) of `openscenegraph`, `osgearth` and `ossim` packages for targets:
```
MXE_TARGETS := i686-w64-mingw32.static i686-w64-mingw32.shared \
x86_64-w64-mingw32.static x86_64-w64-mingw32.shared
```
> osgViewer: fix build with GCC < 6.x

- src/osgPlugins/dae/daeRMaterials.cpp
The collada loader would crash when processing effects that didn't have a technique defined.
> Fix crash in Collada loader

- src/osgPlugins/dae/ReaderWriterDAE.cpp
- src/osgPlugins/dae/daeRMaterials.cpp
- src/osgPlugins/dae/daeReader.h
The Collada loader uses the global registry options when loading images, instead of the options passed into the loader. This patch modifies the loader to use the specified options to load images.
> Use options when loading images in Collada loader

- src/osgPlugins/gif/ReaderWriterGIF.cpp
The gif loader was incorrectly setting pixels as transparent in certain animated gifs. It was ignoring the disposal method value in the extension block and always overwriting the alpha value in each frame. It is common for some animated gifs to set the disposal method so that the previous alpha value is retained. This patch modifies the loader to respect the disposal method flag.
> Fix handling of alpha values in animated gifs

- src/osgText/String.cpp
Hi Robert,
While testing some of my code against UTF-8 I found that String::createUTF8EncodedString() was failing for 4-byte UTF8 sequences.  This should patch in support.  Thanks.
- Dan
> osgText::String:createUTF8EncodedString() now supports 4-byte UTF-8 strings (code points over 0x100000)

- src/osgPlugins/fbx/WriterNodeVisitor.cpp
- src/osgPlugins/fbx/WriterNodeVisitor.h
The fix to allow the export of orphaned Geometry nodes accidentally
duplicated those geometry nodes in 'normal' scene trees. This commit
refactors the code to rely on the visitor to traverse the Geometry as
opposed to traversing the Geometry in the Geode visit and the Geometry
visit.
> Fix duplicate geometries in FBX export.

- src/osgDB/DatabasePager.cpp
Hi Robert,
I found some models that did not unload from memory after opening a different model in our viewer, and this pr allows them to properly unload. The problematic nodes are children of a pagedLOD node, I'm not sure if the problem is only the databaseRequest holding a ref_ptr in the temp object cache or that child nodes (nested pagedLODs) make a copy of the options.
> clear temp objectCache in databaseRequest

- include/osgViewer/Viewer
Hi Robert,
I get quite a few warnings in visual studio 15.9.5.
The "using" statements you added doesn't solve this (I assume it solved something else, I did not try to remove them). An explicit call to the base class removes the warnings, and if I remember properly that's the solution we used last time as well.
I checked this on the OpenScengraph-3.6 tree, but the master tree seems to have the same code.
e:\osg\36\laurens\openscenegraph\include\osgviewer\viewer(130): warning C4250: 'osgViewer::Viewer': inherits 'osg::View::osg::View::resizeGLObjectBuffers' via dominance (compiling source file E:\osg\36\laurens\OpenSceneGraph\src\osgViewer\HelpHandler.cpp)
e:\osg\36\laurens\openscenegraph\include\osg\view(164): note: see declaration of 'osg::View::resizeGLObjectBuffers' …
> fix MSVC warning C4250: inherits 'X' via dominance (94x)

- src/osgPlugins/fbx/fbxMaterialToOsgStateSet.cpp
The FBX plugin may fail texture lookup even if the texture is located in the same folder as the model file. 
Currently the plugin checks the following locations:
1.  The absolute filename appended to the current directory _(Works well when the absolute filename is a pure filename, but fails when the absolute filename is a complete path)_
2. The absolute filename only. _(Works well assuming the texture can be found at exactly this complete path)._
3. The relative filename appended to the current directory _(requires that the texture is placed at exactly in the same relative location to the model as the file was saved in)._
This change adds a fourth option:
4. The pure filename part of the absolute filename (i.e. without any paths) appended to the current directory. This will look in the …
> Add search location for textures in FBX plugin

- include/osg/OcclusionQueryNode
- src/osg/OcclusionQueryNode.cpp
Regarding a race condition setting _validQueryGeometry, it's already protected by the _computeBoundMutex, which is already used for updating the query geometry.
The _computeBoundMutex isn't locked when the query geometry is accessed in the rest of the code, so I suspect that accessing _validQueryGeometry should also be fine, otherwise there currently already is a race condition.
About the validity of the query geometry, what I found in our application is, that the
box has to be at least >=0.01 in all three dimensions, otherwise the occlusion query
doesn't yield correct results.
If you like I could also add such a test to OcclusionQueryNode.
> Ensure valid occlusion query geometry

- .gitignore
The `.gitignore` was missing some files from an in-source build. Some of these were from the documentation build process, while another was the `.vs` folder Visual Studio 2015 and later use to store machine-specific files.
I've tried to put them in what seemed like the most sensible places as the `.gitignore` file is nicely sorted and I didn't want to mess that up.
> Add missing files to .gitignore

- src/osgParticle/ParticleSystem.cpp
If OSG is compiled with OSG_USE_FLOAT_MATRIX=ON, using Matrixd here leads to rather wasteful Matrixd<=>Matrixf conversions when particles are updated. osg::Matrix, however, is always typedef'd to the correct type, so the minor overhead will no longer be present.
> Avoid unnecessary matrix type conversion in osgParticle

- src/osgAnimation/StackedTransform.cpp
The osgAnimation::StackedTransform class will not update the matrix if the state is going from a non-identity to identity value. For example, if you have a stepped animation that is cycling the scale of an object between (1,1,1) and (2,2,2), the object will scale to (2,2,2) and remain at that value, since (1,1,1) is considered identity and will not dirty the matrix.
I've modified the StackedTransform::update class so that it will update the matrix, regardless of the element identity state. It will still check if the element is identity when apply the value to the new matrix.
> Fix osgAnimation transform not updating in some cases

- src/osg/GLExtensions.cpp
There are two types of Geometry Shaders in OpenGL.
One is provided by `GL_EXT_geometry_shader4` and `GL_ARB_geometry_shader4` and requires that certain parameters are set with calls to `glProgramParameteri` before the program is linked. Without these extensions, the calls are erroneous.
The other is provided by OpenGL 3.2 as a core feature and by the GLES extensions `GL_EXT_geometry_shader` and `GL_OES_geometry_shader` and requires these parameters to be set in the GLSL source itself.
The value of `isGeometryShader4Supported` is being used [here](https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/Program.cpp#L709-L714) to determine if the `glProgramParameteri` calls should occur, so it should only be `true` when one of the extensions requiring them is present.
Resolves …
> Resolve OpenGL error caused by confusion between geometry shader implementations

- include/osgParticle/LinearInterpolator
Since we already know what interpolate is going to do in a linear interpolator, it's really unnecessary to interpolate each component of a vector separately. They can simply be interpolated (surprise) linearly between each other directly for a slight performance improvement.
> Override default behavior for linear vector interpolations

- include/osg/Node
- include/osg/OccluderNode
- src/osg/Group.cpp
- src/osgParticle/ParticleProcessor.cpp
- src/osgParticle/ParticleSystemUpdater.cpp
1. asOccluderNode virtual method was added to avoid costly dynamic casts in Group child insertion and removal.
2. Unnecessary asCullVisitor usage in osgParticle was replaced with a type check, since that's what is usually done for the purpose and it makes the code intention more clear - the resulting pointer to a cull visitor isn't actually used beyond an existence check.
A project I'm contributing to has plans to move to upstream OSG from a barely maintained forked 3.4.1 and I'm aiming to get some of the used changes to upstream, so it'd be nice if these could also get into 3.6 branch if possible but if not, well, I won't complain.
> Get rid of some type conversions

- src/osg/GLExtensions.cpp
In compatibility mode (OpenGL 2.1), glVertexAttribDivisor is available
via glVertexAttribDivisorARB on macOS.
> macOS support for glVertexAttribDivisor with legacy GL

- CMakeLists.txt
- src/osgViewer/CMakeLists.txt
Build system on macos was broken after #727
(if ANDROID => **None** FORCE else => **X11** FORCE)
This PR fixes configuration for macos and ios.
>  CMake: OSG_WINDOWING_SYSTEM fixed

- src/osgPlugins/fbx/WriterNodeVisitor.cpp
- src/osgPlugins/fbx/WriterNodeVisitor.h
Saving fbx function creates redundant fbx nodes, including one empty parent node for the whole scene and one empty node for each Geometry. Every time you load the model and save to file, these redundant nodes would accumulate, so after repeating load&save for some times the hierarchy become a mess. This commit fixes the problem and ensures fbx file remains the same after each load&save operation.
> fix fbx redundant node issue

- src/osgSim/LightPointNode.cpp
Ran into a compile error after removing the #define OSGUTIL_RENDERBACKEND_USE_REF_PTR (to see if that would render faster on windows; it does not).
Fix applies to master as well.
Laurens.
> fix compile error if OSGUTIL_RENDERBACKEND_USE_REF_PTR not defined in include/osgUtil/RenderLeaf

- include/osgDB/StreamOperator
windows std::endl is a template with different addresses in different dll's
causing the indentation to fail for osgt files.
Fix applies to master as well.
Laurens.
> fix indentation for osgt files for windows dynamic library build.

- src/osgPlugins/tga/ReaderWriterTGA.cpp
This PR makes various improvements to the TGA loader, including adding support for type 3, 9 and 11 TGA images. While it's fairly large, each individual commit is intended to be easily reviewable on its own.
It's been tested with this suite of TGA files: https://github.com/ftrvxmtrx/tga/tree/master/testdata. This is comprised of Truevision's official TGA 2.0 Utilities Package plus some extras, and seems to be the same test suite that lots of other TGA loaders are using.
> Various TGA improvements

- src/osgPlugins/fbx/ReaderWriterFBX.h
Hi Robert,
I noticed a type in the function name for fbx writeObject, and while I'm not sure if there is any code path that might call this function I suppose it's better to fix this anyway.
Laurens.
> fix typo in ReaderWriterFBX: writObject -> writeObject

- src/osg/VertexArrayState.cpp
_vertexAttribArrays must be 'shared'
NOTE: Issue #439 will be really fixed ;)
> VertexArrayState's lazy disabling of vertex attributes mechanism major fix

- src/osgViewer/GraphicsWindowWin32.cpp
Num lock state was never checked during remapping keypad keys on Windows. Now when num lock is  active, keypad numeric keys and keypad delimeter key should work as expected (return KEY_KP_0 to KEY_KP_9 and KEY_KP_Decimal respectivly).
> Fix not checking num lock state when remapping keypad keys on Windows.

- src/osgPlugins/fbx/fbxRMesh.cpp
Due to a copy-paste typo, multiple UV channel where not correctly imported.
Also, as an optimization, pointers comparison could be used rather than strcmp() as static const string coming from FBX SDK are compared.
> fbx reader: fixed multi uv channel support

- CMakeLists.txt
Current FindWxWidgets.cmake allows to specify OPTIONAL components, unfortunately
this broke the (deprecated) use of wxWidgets_USE_LIBS.
Fixes: #779
> Fix wxWidgets COMPONENTS specification, deprecated usage broken with CMake 3.14

- src/osgText/CMakeLists.txt
- src/osgText/Font.cpp
If fontconfig was found when compiling osg, osgText will first search for font names in the paths provided by fontconfig. This commit adds a new optional dependency to Fontconfig.
Fixes #778
> Fix 'Incorrect default location for true type fonts on openSUSE'

- CMakeLists.txt
I have moved the `PROJECT` stanza before the conditionals, because
otherwise expressions like `IF(MINGW)` always fail.
> Avoid that mingw cross-compilation choosing X11 as the windowing system.

- src/osgPlugins/obj/OBJWriterNodeVisitor.cpp
- src/osgPlugins/obj/OBJWriterNodeVisitor.h
- src/osgPlugins/obj/ReaderWriterOBJ.cpp
When using osgconv to convert an osgb file into an obj file, you cannot export the texture file contained in it, even if -O OutputTextureFiles is added.
So I modified the obj plugin to support the export of texture files.
> fix obj-Plugin export texture file

- src/osgPlugins/dds/ReaderWriterDDS.cpp
So I've added in support for reading this rather obscure format by reconstructing the image data into a full-sized RGBA image. Used the GIMP DDS plugin for reference, apparently the 256 color palette is put right after the header. Alpha flag is never used.
I used these images to test it.
[examples.zip](https://github.com/openscenegraph/OpenSceneGraph/files/3511525/examples.zip)
> DDS plugin: add support for DDPF_PALETTEINDEXED8 pixel format reading

- src/osgDB/DynamicLibrary.cpp
This helps to debug loading dynamic libraries in an environment without implemented "dlopen". For example emscripten with static compiled OSG.
> Debugging: Hint to debug LoadLibrary issues

- include/osg/OcclusionQueryNode
- src/osg/OcclusionQueryNode.cpp
When the query geometry gets reset to its default then its
vertices have to be updated by the bounding box dimensions of
the current children of the OcclusionQueryNode.
> OcclusionQueryNode: fix resetting to default query geometry

- src/osgPlugins/dae/README.txt
Hi,
This is a really minor fix, as the documentation of the CMake variables is outdated.
> fix outdated dae readme

- src/osg/GLExtensions.cpp
examples/osgpointsprite and examples/osgpoints are broken due to
incorrect isPointSpriteModeSupported state in legacy OpenGL.
> Init isPointSpriteModeSupported correctly.

- src/osg/Image.cpp
Using the textureatlasbuilder on (DXT) compressed textures can crash on these errors. I guess I wrote the code myself, sorry about the bug.
Same problem is in master, I will supply a PR for that as well.
Laurens.
> fix copySubImage crash on compressed files

- src/osgPlugins/dds/ReaderWriterDDS.cpp
The DDS plugin is not able to load floating point RGB images saved out by itself. There doesn't appear to be a fourcc code for RGB float/half-float data, so I added the appropriate entries to the RGBFormat table so the images can be loaded properly.
> Support reading RGB float DDS images

- src/osg/Matrix_implementation.cpp
The diagonal elements were not copied from the source matrix.
> Fix bug in matrix transpose() and transpose3x3

- src/osgPlugins/tga/ReaderWriterTGA.cpp
Replace operators for implicit type conversion by explicit data() method to access implementation pointer and subscript operator to access element by index just like in std::vector.
```
src/osgPlugins/tga/ReaderWriterTGA.cpp:455:22: error: use of overloaded operator '==' is ambiguous (with operand types 'SafeArray<unsigned char>' and 'long')
if (colormap == NULL)
~~~~~~~~ ^  ~~~~
src/osgPlugins/tga/ReaderWriterTGA.cpp:525:16: error: use of overloaded operator '==' is ambiguous (with operand types 'SafeArray<unsigned char>' and 'long')
if (buffer == NULL || linebuf == NULL)
~~~~~~ ^  ~~~~
src/osgPlugins/tga/ReaderWriterTGA.cpp:525:35: error: use of overloaded operator '==' is ambiguous (with operand types 'SafeArray<unsigned char>' and 'long')
if (buffer == NULL || linebuf == NULL)
~~~~~~~ …
```
> Fix clang 8 & libc++ build errors

- src/osgViewer/CMakeLists.txt
`-lXinerama` breaks the build as the linked does not know where to find the library. Using properly detected library fixed this.
> Fix linking with Xinerama

- src/OpenThreads/pthreads/CMakeLists.txt
- src/OpenThreads/pthreads/PThread.cpp
On FreeBSD, `pthread_setaffinity_np` lives in separate `pthread_np.h` header, and also `cpuset_t` is named differently.
> Add FreeBSD-specific code bits for pthread_setaffinity_np support

- src/osgPlugins/tiff/ReaderWriterTIFF.cpp
As the title.
Code like this:
```
...
tex = new osg::Teture2D();
tex->setImage(osgDB::readImageFile("x.tiff"));
...
printf("%u\n", tex->getImage()->getInternalTextureFormat());
```
The value is 3.
So i checked the plugin tiff, found that using number of components instead of which it should be.
Also plugin tga has similar problem.
I try to fix plugin tiff first, then back to work, bypassing this problem manually.
> getInternalTextureFormat() failed after reading a tiff file

- packaging/cmake/OpenSceneGraphConfig.cmake.in
Following statement will never set OpenSceneGraph_osgText_FOUND to TRUE:
```
FIND_PACKAGE(OpenSceneGraph REQUIRED COMPONENTS osgViewer osgText CONFIG)
```
It cause cmake failure, the error message is confusing:
```
Found package configuration file:
/usr/local/osg/gl2/lib/cmake/OpenSceneGraph/OpenSceneGraphConfig.cmake
but it set OpenSceneGraph_FOUND to FALSE so package "OpenSceneGraph" is
considered to be NOT FOUND.
```
I know one doesn't need to add osgText after osgViewer, but it should not cause an error
with confusing message.
> Set OpenSceneGraph_${component}_FOUND to TRUE for existing target.

- examples/osgtext/osgtext.cpp
Second text alignment is wrong when "--alignment" specified.
3D text radius is too small, only SCREEN_COORDS can be seen.
Text position should multiply radius.
> Fix a typo and invisible 3dtext in examples/osgtext.

- src/osgText/CMakeLists.txt
Add Fontconfig to TARGET_LIBRARIES cause osg3::osgText target looking for
openscegraph-Fontconfig-import-targets.cmake, which doesn't exists.
> Fontconfig should be external library.

- src/osg/GLExtensions.cpp
> GLExtensions's isPBOSupported and isVAOSupported flags fixed

- src/osgPlugins/tga/ReaderWriterTGA.cpp
Hi Robert,
I get a compile error in the debug config in Visual Studio Community 15.9.18 & 16.4.1:
OpenSceneGraph\src\osgPlugins\tga\ReaderWriterTGA.cpp(725): error C2676: binary '+': 'SafeArray<unsigned char>' does not define this operator or a conversion to a type acceptable to the predefined operator
This was introduced by "Fix clang 8 & libc++ build errors" from "elsid" (22/11/2019).
This is a PR for OpenScenGraph-3.6, I will make a PR for master too.
> fix debug compile error for ReaderWriterTGA

- examples/osgAndroidExampleGLES2/jni/OsgMainApp.cpp
Android GLES2 example use event queue without initializing window rectangle with graphics context,that produce navigation error.
> Fix navagation error about Android GLES2 example.

- include/osg/GLDefines
compiling current master with msvc 2019 (16.4) yields 3 compile errors:
OpenSceneGraph\src\osg\BufferObject.cpp(221,34): error C2065: 'GL_MAP_PERSISTENT_BIT': undeclared identifier. 
Fixed by adding a (conditional) define.
> add GL_MAP_PERSISTENT_BIT define for outdated gl.h users (like msvc).

- include/osgUtil/RenderStage
This is mostly for debug purpose, users should get a chance to to recursively parse `RenderStages`.
I'm writtng a `RenderPrinter` to print all  `RenderBin`, `RenderLeaf` in all RenderStages by render order, can't do it  without these functions.
> Add getPreRenderList, getPostRenderList to RenderStage.

- src/osgPlugins/las/ReaderWriterLAS.cpp
Hi Robert,
there is a bug in the las reader:
the final drawable needs to be added to the geode before iterating all drawables of the geode for recentering.
The option "noReCenter" can be used as work-around for this bug.
This PR is for branch OpenScenGraph-3.6, but the same changes apply to master as well.
> ReaderWriterLAS recenter bug fixed, final batch of points was missed in translating the center point.

- src/osgDB/DatabasePager.cpp
fix bug in ProxyNode with DEFER_LOADING_TO_DATABASE_PAGER causing crash when children reorder during load.
Hi Robert,
I got a crash while using a proxyNode to load a few files from a remote webserver, using mutiple database pager threads. While the pagedLOD can rely on the children to be added in fixed order, the children of a proxyNode can be added in any order.
This patch applies both to 3.6 and master branch.
> fix bug in ProxyNode with DEFER_LOADING_TO_DATABASE_PAGER

- CMakeModules/FindGTA.cmake
- CMakeModules/FindGtkGl.cmake
- CMakeModules/FindPoppler-glib.cmake
- CMakeModules/FindRSVG.cmake
- src/osgViewer/CMakeLists.txt
Including FindPkgConfig directly into scripts is not a recommended practice.
Doing so will cause CMake to complain with a warning.
Replaced with find_package(PkgConfig QUIET)
> Improve PkgConfig usage

- src/osgPlugins/zip/ZipArchive.cpp
Hi Robert,
Here is a fix to ZipArchive to make sure the archive is closed in the destructor.  I was running a test loading many files out of a zip with archive caching turned off and noticed it eventually stopped working b/c it was opening the zip file on each read but never closing it so it would run out of file handles.
Thanks!
Jason
> Closing ZipArchive in destructor

- src/osgPlugins/x/types.h
Compile with latest MSVC 16.6.0 Preview Release, got error message:
> osgPlugins\x\types.h(41,20): error C7626: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes (compiling source file ...3rdparty\OpenSceneGraph\src\osgPlugins\x\mesh.cpp)
The fix was just to give it a name, which will never be used. I picked Vector_struct, feel free to improve.
> Name unnamed typedef struct {...} to fix MSVC error

- src/osgPlugins/tga/ReaderWriterTGA.cpp
Some files which are malformed TGA 2.0 files are technically valid TGA 1.0 files. For example, an image that just happened to have pixel data matching the TGA 2.0 footer or files created by buggy TGA 2.0 writers and were only ever fed to TGA 1.0 readers.
One such example from a Morrowind mod is attached:
[tx_comberry_01_p.zip](https://github.com/openscenegraph/OpenSceneGraph/files/4471548/tx_comberry_01_p.zip)
This file has a header saying it has eight attribute bits. A TGA 1.0 reader is free to interpret them how it wants (e.g. as alpha or stencil, or just ignoring them). A TGA 2.0 reader is supposed to check for a footer directing it to an extension area, which, if present, will have a field saying what those bits mean. The file's extension area says it doesn't have any such bits (which …
> Add option to treat all TGA files as TGA 1.0

- src/osg/Texture1D.cpp
- src/osg/Texture2D.cpp
- src/osg/Texture2DArray.cpp
- src/osg/Texture2DMultisample.cpp
- src/osg/Texture3D.cpp
- src/osg/TextureCubeMap.cpp
- src/osg/TextureRectangle.cpp
a quick fix for https://github.com/openscenegraph/OpenSceneGraph/issues/935 a minor problem that affect master too
> [osg3.6] prevent immutability setting when textureobject is taken from orphans

- src/osgPlugins/cfg/ConfigParser.cpp
The "register" keyword is deprecated as of C++17. (https://en.cppreference.com/w/cpp/keyword/register) Removing it is necessary to build with clang10+.
> Remove register keyword (deprecated in C++17/20)

- src/osg/GLExtensions.cpp
GLExtensions::glTexStorage2DMultisample in fact called glTextureStorage2DMultisample which expects texture object instead of texture target
> Fixed creation of multisample textures

- src/osgText/Text.cpp
Matches what the rest of the properties are doing & avoids unnecessary
computation.
> Return early in osgText::Text property setters

- include/osg/Callback
- include/osg/Camera
- src/osg/OcclusionQueryNode.cpp
The OcclusionQueryNode uses camera callbacks for its implementation. If the camera in the scenegraph already had callbacks set, then it didn't work, because it expected to be the only one setting callbacks.
With this fix the implementation should just work, regardless if callbacks are already set or not.
> Fix camera callbacks of OcclusionQueryNode

- CMakeModules/FindFontconfig.cmake
cmake 2.8.12 cannot parse it. From the looks of it this sort of markup only needs to be parsable when building cmake v3 itself.
> comment out cmake internal help markup

- include/osgDB/PluginQuery
- include/osgDB/ReaderWriter
- src/osgDB/PluginQuery.cpp
- src/osgDB/ReaderWriter.cpp
- src/osgPlugins/curl/ReaderWriterCURL.cpp
- src/osgPlugins/txp/ReaderWriterTXP.h
With this pull request osgconv shows which environment variables are supported by plugins for example:
```
Plugin /usr/lib64/osgPlugins-3.6.5/osgdb_curl.so
{
ReaderWriter : HTTP Protocol Model Reader
{
features   : readObject readImage readHeightField readNode writeObject writeImage writeHeightField writeNode 
protocol   : ftp                        Read from ftp port using libcurl.
protocol   : ftps                       Read from ftps port using libcurl.
protocol   : http                       Read from http port using libcurl.
protocol   : https                      Read from https port using libcurl.
extensions : .*                         Passes all read files to other plugins to handle actual model loading.
extensions : .curl                      Pseudo file extension, used to …
```
> Add support for showing environment variables provided by osg plugins

- include/osg/GLExtensions
- src/osg/GLExtensions.cpp
The s_glExtensionSetList could be deleted while pointers to
GLExtension objects were still held e.g., by
VertexArrayStateManager, causing a segfault. This patch uses an
observer pointer to not access already-deleted data.
> Fix GLExtensions static order of deletion bug

- src/osgPlugins/dae/ReaderWriterDAE.cpp
This PR fixes the pluginOptions.options being cloned in std::istream -method, similar as it's done in std::string -method of ReadNode. This enables the use of Options base class features, e.g. setReadFileCallback( ReadFileCallback* cb).
> Clone pluginOptions.options

- src/osgPlugins/dae/daeRSkinning.cpp
Dae-plugin doesn't seem to transfer dae-node names to osg-nodes. This PR browses through dae-object, and sets the names for the skeleton and bones.
> Get names of bones and skeleton to osg nodes

- src/osgPlugins/dae/daeRMaterials.cpp
This is an artificial limit, and prevents using custom virtual file system or relative paths in custom image read callbacks. Removing that enables using dae image paths like "textures/texture.png". Removing the check results in passing the filepaths directly to cdom::uriToNativePath.
> Remove "file" protocol check

- src/osg/State.cpp
This PR solves this bugs (_if osg::ShaderComposer used_) :
1) Multiple redundant glUseProgram(0) -> glUseProgram(program) calls
**This was wrong:**
a) AttributeStack should not be changed by ShaderComposer
b) Pragma(tic) mechanism must be applied after ShaderComposer
2) Using of Program via core StateSet mechanism while using ShaderComposer mechanism
**This condition was wrong**:
`if (previousLastAppliedProgramObject == _lastAppliedProgramObject || _lastAppliedProgramObject==0)`
PS
It's hard to understand the diff because the order of lines has been changed
> ShaderComposition mechanism on the osg::State fixed

- CMakeLists.txt
Looks like [10-ish](https://opensg-users.sf.narkive.com/afHDE38B/mixed-up-compiler-settings-osg-disable-microsoft-secure-cxxx-off-but-secure-scl-set) years ago there was proper support to disable debug iterators on windows. This seems to have been moved incorrectly to CMake.
In "modern" versions (VS2010 and higher) the ```_ITERATOR_DEBUG_LEVEL``` will supersede both ```_SECURE_SCL``` ```_HAS_ITERATOR_DEBUGGING```
> updated cmake to properly disable debug iterators on windows

- src/osgPlugins/zip/unzip.cpp
> Fix Duplicate symbols when linking OSG as a static library

- include/osg/Callback
Fixes travis, which explictly requires c++98
> include/osg/Callback: nullptr -> NULL

- include/osgAnimation/Keyframe
```
include/osgAnimation/Keyframe:108:53: warning: declaration of 'iterator' shadows a member of 'osgAnimation::TemplateKeyframeContainer<osgAnimation::TemplateCubicBezier<double> >' [-Wshadow]
108 |             for(std::vector<unsigned int>::iterator iterator = intervalSizes.begin() ; iterator != intervalSizes.end() ; ++ iterator) {
|                                                     ^~~~~~~~
include/osg/MixinVector:39:44: note: shadowed declaration is here
39 |     typedef typename vector_type::iterator iterator;
|                                            ^~~~~~~~
```
Please also cherry-pick into 3.6 when merging
> osgAnimation/Keyframe: Fix -Wshadow warning

- include/osgViewer/GraphicsWindow
Follow-up to #1027
---
Please also cherry-pick to 3.6
> include/osgViewer: Fix typo

- src/osgPlugins/dae/daeReader.cpp
Related to https://github.com/openscenegraph/OpenSceneGraph/issues/1007
Tested to work with Qt5.
> Use c-locale with std::istream

- include/osg/BoundingSphere
- include/osg/GLExtensions
- include/osg/Quat
- src/osg/glu/libtess/tess.cpp
- src/osgPlugins/dds/ReaderWriterDDS.cpp
- src/osgPlugins/gles/IndexMeshVisitor.cpp
- src/osgPlugins/gles/glesUtil
- src/osgPlugins/ive/DataInputStream.cpp
- src/osgPlugins/ive/DataOutputStream.cpp
- src/osgPlugins/osc/OscReceivingDevice.cpp
- src/osgUtil/MeshOptimizers.cpp
Cherry-picked https://github.com/openscenegraph/OpenSceneGraph/commit/e0d5e4b0ffa382ea0cf1d3290937722950a9ed80
Identical except for the changes to `MatrixTemplate`, which does not exist in 3.6
> Back-port (cherry-pick) warnings fixes into 3.6

- CMakeLists.txt
Android-specific macros aren't needed in some cases, e.g. a much easier way to find packages is to simply specify the correct `CMAKE_FIND_ROOT_PATH`.
The `ANDROID_3RD_PARTY` macro interferes with this. Adds an option to disable it.
WIN32 build is in a similar situation, the new option affects it also.
---
Please also cherry-pick into 3.6 when merging (confirmed that this cherry-picks cleanly and works)
> CMakeLists.txt: OSG_FIND_3RD_PARTY_DEPS option

- src/osg/FrameBufferObject.cpp
Was just missed when you did the inital work I think.
One thing I think would be worth looking at is a way to set baseViewIndex and numViews manually. I can't think of a way though without adding new variables somewhere.
Users might have a situation where they want to render more views than the hardware is capable of in a single pass but they may also want to keep all the views in a single texture array. If they could set the baseViewIndex and numViews manually they could say render me from 0-3 in one pass then 4-7 in another pass.
Just a thought.
> Setting numViews value in glFramebufferTextureMultiviewOVR call

- include/osgDB/Registry
A Registry instance may be accessed before the global mutex, e.g. via `osgText::Font::getDefaultFont()`  here:
https://github.com/openscenegraph/OpenSceneGraph/blob/e77f50371ce6ab05ee0c523fc7a4604ad639e047/src/osgText/Font.cpp#L49
This leads to the Mutex being destroyed before the Registry is destroyed.
This causes a crash at exit, as described in #1048.
Fixes #1048.
---
Please also merge into 3.6 (applies cleanly)
> Ensure global Mutex is initialized before Registry

- src/osg/DisplaySettings.cpp
- src/osgPlugins/cfg/ConfigParser.cpp
- src/osgPlugins/cfg/ConfigParser.y
With C++17, Windows headers must not be included after `using namespace std;`.
Windows headers define a `byte` type internally and `using namespace std`
causes it to conflict with `std::byte`:
error C2872: 'byte': ambiguous symbol
MSVC thread: https://developercommunity.visualstudio.com/t/error-c2872-byte-ambiguous-symbol/93889
> Fix C++17 MSVC compilation error

- examples/osgfpdepth/osgfpdepth.cpp
- src/osg/GLExtensions.cpp
`isRenderbufferMultisampleCoverageSupported()` should not return true if the extension is not supported.
Fixes #1028
> Check GL_NV_framebuffer_multisample_coverage

- src/osg/GLExtensions.cpp
Gives **GPU** stats while using GLESs and WebGL1
> OpenSceneGraph 3.6 improvement: GL_EXT_disjoint_timer_query extension added

- src/osgText/TextBase.cpp
_lineCount can be 0 if the TextBase has no text, so we get underflow if the alignment is one of the *_BOTTOM_BASE_LINE. Empty text nodes seem to come up in some of the .dxf files our users are importing.
I've worked around the bug in our code for now by deleting the empty text nodes on load.
> Fix bounds for empty text nodes

- include/osg/ref_ptr
Use conditional compilation to make it work only with C++11 support.
This gives a performance boost for inserting and erasing from a middle of a `std::vector<osg::ref_ptr>` because no reference counting is done while elements are shifted. Insert example is `Group::insertChild` function [here](https://github.com/openscenegraph/OpenSceneGraph/blob/d64ad2e654001a4323a7fb39fa3d937ae71f1646/src/osg/Group.cpp#L98) and erase example is `Group::removeChildren` function [here](https://github.com/openscenegraph/OpenSceneGraph/blob/d64ad2e654001a4323a7fb39fa3d937ae71f1646/src/osg/Group.cpp#L199).
In the specific OpenMW location loading case total cost of `Group::insertChild` is reduced by 11 times and `Group::removeChildren` by 13 times. Overall this reduces specific location loading by half. For …
> Add move constructor and move assignment operator to ref_ptr

- src/osg/DisplaySettings.cpp
DisplaySettings::setDisplaySettings sets _shaderHint from itself (potentially uninitialized)
> Fix _shaderHint bug in DisplaySettings::setDisplaySettings
