openscenegraph/OpenSceneGraph

.gitignore
Added patterns for visual studio generated files as well as for files
generated by CMake for windows only.
This is identical to previously closed PR #55
=> GitIgnorePatterns for Visual Studio

include/osgViewer/View, src/osgViewer/CompositeViewer.cpp, src/osgViewer/View.cpp, src/osgViewer/Viewer.cpp
Further improvements are proposed as comments in the diff.
Please comment.
=>  refactor common code from CompositeViewer::checkNeedToDoFrame() and Viewer::checkNeedToDoFrame() into View

src/osgPlugins/curl/ReaderWriterCURL.cpp, src/osgPlugins/curl/ReaderWriterCURL.h
Added OSG_CURL_SSL_VERIFYPEER option to the curl plugin to allow connecting to secure servers without the certificate
=> Added OSG_CURL_SSL_VERIFYPEER option to the curl plugin

include/osg/Capability
splitting up the previous large pull request
=> bugfix: wrong class name in META_Object macro for osg::Enablei /disable

include/osgAnimation/BasicAnimationManager, src/osgAnimation/BasicAnimationManager.cpp
added copyconstructor for osgAnimation::BasicAnimationManager
=> Submissions2f

src/osgPlugins/dae/daeWGeometry.cpp, src/osgPlugins/dae/daeWSceneObjects.cpp
fix a few warning C4456: declaration of 'X' hides previous local declaration
=> VS2015 dae plugin fix a few declaration of 'X' hides previous

CMakeLists.txt
simple version: disable warning for all msvc versions
=> disable warning C4589 for MSVC

CMakeLists.txt
Hi Robert,
I failed to restore a test for cmake, and this was merged in my previous commit. Someone made a comment about this - no idea who that was. Anyway - here's the correct version.
=> fix error in CmakeLists: CMAKE_CXX_COMPILER_VERSIO

src/osg/glu/libtess/tess.cpp, src/osgPlugins/osgjs/Animation
fix a few minor warnings from Visual Studio 2015
=> Submissions12

README.md
=> osg now requires cmake 2.8.0

src/osgPlugins/ktx/ReaderWriterKTX.cpp, src/osgPlugins/ktx/ReaderWriterKTX.h
added the ability to write .ktx files
=> ktx write support

include/osg/LOD, include/osg/PagedLOD
Documentation has been added for their default constructors. Furthermore, the consequences of different center modes have been explained. A comment regarding the setting of the radius has been fixed.
=> Addition of documentation for LOD and PagedLOD

.travis.yml, CMakeLists.txt, src/CMakeLists.txt
Hi Robert,
I finally came up with this construct to make the travis ci apple build complete without error. 
=> split travis-ci apple build into two jobs to avoid job time limit.

include/osgDB/SharedStateManager, include/osgGA/EventVisitor, include/osgUtil/DisplayRequirementsVisitor, include/osgUtil/DrawElementTypeSimplifier, include/osgUtil/GLObjectsVisitor, include/osgUtil/MeshOptimizers, include/osgUtil/ShaderGen, include/osgUtil/Simplifier, include/osgUtil/SmoothingVisitor, include/osgUtil/TriStripVisitor, include/osgUtil/UpdateVisitor, src/osg/GraphicsCostEstimator.cpp, src/osgDB/SharedStateManager.cpp, src/osgPlugins/sdl/ReaderWriterSDL.cpp, src/osgShadow/OccluderGeometry.cpp, src/osgShadow/ViewDependentShadowMap.cpp, src/osgUtil/DisplayRequirementsVisitor.cpp, src/osgUtil/DrawElementTypeSimplifier.cpp, src/osgUtil/GLObjectsVisitor.cpp, src/osgUtil/MeshOptimizers.cpp, src/osgUtil/ShaderGen.cpp, src/osgUtil/SmoothingVisitor.cpp, src/osgUtil/TriStripVisitor.cpp
I did a search for "apply(osg::Geode" to find more legacy code that does not work properly for drawables attached directly in the scene graph. Fixes included.
While I have not tested these apart from compiling and a quick run through examples, it seems unlikely that things are broken more so than they were before ;)
=> More fixes for Geode/Drawable handling in visitors

examples/osgvertexattributes/osgvertexattributes.cpp
osg_ModeViewMatrix -> osg_ModelViewMatrix
=> Fixed typo

include/osgUtil/Optimizer, src/osgPlugins/ktx/ReaderWriterKTX.cpp, src/osgUtil/Optimizer.cpp
Fix the MergeGeometryVisitor to work on geometries not attached to a Geode, plus some minor fixes. Tested with several scenes.
=> MergeGeometryVisitor fix

CMakeModules/FindFBX.cmake
apple (clang) support not tested - I have no apple.
=> added FBX SDK 2017.1 and try to add apple (clang) support.

src/osgViewer/GraphicsWindowWin32.cpp
Added PEN input support to GraphicsWindowWin32 with the WM_POINTER* framework, available since Windows 8.
PEN inputs emulates the mouse motion and click with the left mouse button.
Fallback on existing WM_TOUCH implementation for actual touch inputs, to minimize code change.
POINTER structures are declared if win sdk version is minor than Win8, the additional method is loaded at runtime with the same strategy used by the existing touch implementation.
Tested on Win8 tablets.
=> Added PEN input support to GraphicsWindowWin32 with the WM_POINTER*

src/osgWrappers/serializers/osg/CallbackObject.cpp, src/osgWrappers/serializers/osgVolume/MultipassTechnique.cpp, src/osgWrappers/serializers/osgVolume/VolumeScene.cpp
=> add new serializers

src/osgPlugins/lua/LuaScriptEngine.cpp
=> few fixes for lua Matrix support..

src/osg/KdTree.cpp, src/osgUtil/LineSegmentIntersector.cpp
=> Fixes kdtree building

src/osgPlugins/osg/BinaryStreamOperator.h
Size is written on 8 bytes, to accommodate arbitrarily large block size.
When reading, check of file version is performed for backward compatibility.
Check is for version > 148
I'm allowing edits from maintainers on this pull request, so that you can change the version in this branch before merging back.
The "long long" type on Visual Studio should be supported since VS2005, hopefully that's and old enough compiler.
=> BinaryStreamOperator: read and write block size as long long integer

examples/osggpucull/osggpucull.cpp, include/osg/BufferIndexBinding, include/osg/PrimitiveSetIndirect, src/osg/BufferIndexBinding.cpp, src/osg/PrimitiveSetIndirect.cpp, src/osgWrappers/serializers/osg/PrimitiveSetIndirect.cpp
=> PrimitiveSetIndirect cleanup + serializers

src/osgViewer/GraphicsWindowIOS.mm
Hello, Robert)
After profiling iOS apps in XCode here is a corrected version of GraphicsWindowIOS.
Working on iOS 7.1 and upper (GLES2/GLES3)
KOS
=> osgViewer::GraphicsWindowIOS fixes

src/osgWrappers/serializers/osg/PrimitiveSetIndirect.cpp
=> fix a bug in MDI serializer

include/osg/GLExtensions, src/osg/GLExtensions.cpp
=> Add extensions

include/osg/BoundingSphere
Comparison of the BoundingSphere was not correct.
=> Fix flawed BoundingSphere inequality operator

src/osgAnimation/RigTransformHardware.cpp
That was it all along: 
a bug leading to bad  vertexattribute info in the shader
=> fix a bug in how vertexattributes are filled

examples/osgtext3D/osgtext3D.cpp
Number of glyphs changed while setText.
PS
tabs changed to spaces
=> example_osgtext3d: more options for testing

applications/present3D/present3D.cpp, examples/osgvnc/osgvnc.cpp
added --login option to osgvnc example
Kept the --password option in osgvnc example so the old command line should still work.
Laurens.
=> modified present3D to allow multiple --login arguments like osgViewer.

src/osgPlugins/gz/ReaderWriterGZ.cpp
+remove a useless intermediary string during stream decompression
=> add funcs to read GZ Objects from a stream

src/osg/Texture.cpp
Reverts openscenegraph/OpenSceneGraph#379
=> Revert "    following guidance from OpenGL Common Mistakes:"

examples/osgSSBO/osgSSBO.cpp, examples/osgcomputeshaders/osgcomputeshaders.cpp, include/osg/ComputeDispatch, include/osg/Program, src/osg/CMakeLists.txt, src/osg/ComputeDispatch.cpp, src/osg/Program.cpp, src/osgWrappers/serializers/osg/ComputeDispatch.cpp, src/osgWrappers/serializers/osg/Program.cpp
revoke glDispatch in PCProgram::useProgram
update example
remove numGroups both in Program and its serializer (@robertosfield  retrocompat not maintained)
=> add ComputeDispatch class

src/osgPlugins/logo/ReaderWriterLOGO.cpp
TODO upgrade to a more modern gl (remove glDrawpixel usage)
=> fix logo reader plugin

include/osg/Camera, src/osgUtil/RenderStage.cpp
I added nested callbacks on Camera DrawCallback
It would allow multiple postdrawcallback... Don't know if it's usefull...
I duplicate for all callbacks even if i only use postDrawCallback
=> Camera DrawCallbacks recursivity proposal

src/osgPlugins/zip/ZipArchive.cpp, src/osgPlugins/zip/ZipArchive.h
Nothin to review...  script was the only unimplemented...
=> allow read of script from zip

include/osg/Texture, include/osg/TextureBuffer, src/osg/BindImageTexture.cpp
Not tested but
Does these changes seams wise to you?
=> BindingTextureImage: a more complex condition for  _texture->apply ?

include/osg/GLExtensions, src/osg/GLExtensions.cpp
(codeblocks also remove unsused lineendings...)
a first step toward bufferstorage integration...
=> add more extensions

include/osg/Texture, include/osg/TextureBuffer, src/osg/BindImageTexture.cpp
Reverts openscenegraph/OpenSceneGraph#454
=> Revert "BindingTextureImage: a more complex condition for  _texture->apply ?"

include/osg/ClusterCullingCallback
Addition of general comments about the functionality of ClusterCullingCallback
=> Addition of comments for ClusterCullingCallback

examples/osgemscripten/CMakeLists.txt
Small update to fix build errors.
=> Provide osgemscripten example CMake flags in a more stable way

src/osg/Shader.cpp
Hey Robert!
Just a small change to the master to quiet down shader compilation messages by default.
=> Quiet down shader compilation messages

src/osgPlugins/fbx/fbxMaterialToOsgStateSet.cpp
When loading texture images inside the FBX plugin check that the path
exists before trying to read the image. This is done to avoid
unnecessary warnings inside the readRefImageFile function.
=> Check existence of path before reading image

src/osgPlugins/ffmpeg/FFmpegClocks.cpp, src/osgPlugins/ffmpeg/FFmpegDecoderVideo.cpp
same commit as I made for 3.6 branch applies to master branch too.
=> resolve av sync failure with ffmpeg 3.2 and up

include/osgUtil/MeshOptimizers, src/osgUtil/MeshOptimizers.cpp
IndexMeshVisitor don't reindex indexed
http://forum.openscenegraph.org/viewtopic.php?t=17418
=> add a bool parameter to allow forced reindexation of a mesh

src/osg/Texture.cpp, src/osg/Texture1D.cpp, src/osg/Texture2D.cpp, src/osg/Texture2DArray.cpp, src/osg/Texture2DMultisample.cpp, src/osg/Texture3D.cpp, src/osg/TextureRectangle.cpp
=> TexStorage code cleaning + add feature on Texture2DArray

src/osg/TextureCubeMap.cpp
=> add fixe for Cubemap and TexStorage

include/osg/GLExtensions, src/osg/GLExtensions.cpp, src/osg/Texture.cpp, src/osg/Texture1D.cpp, src/osg/Texture2D.cpp, src/osg/Texture2DArray.cpp, src/osg/Texture2DMultisample.cpp, src/osg/Texture3D.cpp, src/osg/TextureCubeMap.cpp, src/osg/TextureRectangle.cpp
mainly copy/paste from master ..
Take the occasion to add more extensions 
GLExtensions haven't changed since the release so https://github.com/openscenegraph/OpenSceneGraph/pull/606/commits/587e65e674eb9047d2a5a3fdeaa08bab2f1ac37e may be compatible for merging with master
=> Open scene graph 3.6 tex storage

examples/osgsimplegl3/osgsimplegl3.cpp
..as there no feature in the example requiring 3.1
=> use OpenGL 3.0 instead of 3.1 for more compatibility

examples/osgdrawinstanced/osgdrawinstanced.cpp
let a chance to work on intel chipset
=> osgdrawinstanced: add version and required extension to vertex shader

src/osgPlugins/stl/ReaderWriterSTL.cpp
We want to be more accurate for stl files.
=> fix precision numeric for stl writer

CMakeModules/FindFBX.cmake
Just keeping OSG up to date, supporting the latest Autodesk FBX SDK 2019 release: https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2019-0
=> Added support for FBX 2019

src/osgPlugins/dds/ReaderWriterDDS.cpp
I have found that certain image editing programs export DDS images with both the DDPF_FOURCC and DDPF_RGB pixel format flags. The DDS loader will give preference to the DDPF_RGB flag and try to deduce the format from the RGB bit mask values instead of using the more reliable FOURCC flag. This causes some images to not load, even though the FOURCC flag is supported.  I've modified the loader so that it checks for the DDPF_FOURCC flag first, then falls back on deducing the format from the RGB bit masks.
=> Prefer FOURCC pixel format in DDS loader

src/osgShadow/ParallelSplitShadowMap.cpp
=> remove useless code

src/osgShadow/ParallelSplitShadowMap.cpp
fix flickering shadows in SingleThread
=> setup camera Read/Draw Buffer

src/osgPlugins/fbx/fbxRMesh.cpp
Currently the FBX loader does not support loading meshes that contain both skinning and morph target data. The loader will process the skinning data and ignore the morph targets. I've modified the loader so that it will process both sets of data and apply the osgAnimation::MorphGeometry as the source geometry of the osgAnimation::RigGeometry.
=> Support loading FBX meshes with both skinning and morph target data

CMakeLists.txt
fix a problem in main CMakeLists.txt
=> add missing E to ELSIF

applications/osgviewer/osgviewer.cpp, applications/present3D/present3D.cpp, examples/osgCMakeExample/main.cpp, examples/osgCMakeExampleModern/main.cpp
Am I missing something? Replaced this line with a check to see if any points have been added to the path.
Laurens.
=> replaced "if (apm || !apm->valid())"

src/osg/OcclusionQueryNode.cpp
sorry..not very clean commit messages...
=> add enable check in traverseQuery

examples/osgobjectcache/osgobjectcache.cpp, include/osgDB/ObjectCache, include/osgDB/Options, include/osgDB/Registry, src/osgDB/ObjectCache.cpp, src/osgDB/Options.cpp, src/osgDB/Registry.cpp, src/osgPlugins/obj/OBJWriterNodeVisitor.cpp, src/osgPlugins/obj/OBJWriterNodeVisitor.h, src/osgPlugins/obj/ReaderWriterOBJ.cpp, src/osgPlugins/obj/obj.h
This pull request contains fixes for the obj plugin used by http://www.openscenegraph.org/index.php/gallery/use-cases/189-fm-profil
Request is based on #768
=> obj plugin fixes

examples/osgobjectcache/osgobjectcache.cpp, include/osgDB/ObjectCache, include/osgDB/Options, include/osgDB/Registry, src/osgDB/ObjectCache.cpp, src/osgDB/Options.cpp, src/osgDB/Registry.cpp
We are using this fixes in http://www.openscenegraph.org/index.php/gallery/use-cases/189-fm-profil
=> Backport object cache fixes

src/osgPlugins/obj/OBJWriterNodeVisitor.cpp, src/osgPlugins/obj/OBJWriterNodeVisitor.h, src/osgPlugins/obj/ReaderWriterOBJ.cpp, src/osgPlugins/obj/obj.h
=> 3.6 obj plugin fixes

include/osg/io_utils
=> remove return of local pointer

CMakeModules/FindFontconfig.cmake
https://github.com/openscenegraph/OpenSceneGraph/issues/812
=> fix comment block CMake syntax

src/osgPlugins/dds/ReaderWriterDDS.cpp
Before : 3.6 ms
After    : 1.3 ms
(they are means over 1000 tries with ubuntu gcc 7.4.0 )
=> optimize indexed color DDS conversion

src/osgPlugins/fbx/ReaderWriterFBX.cpp
=> Fbx Plugin: added plugin option to set the target axis system.

src/osgPlugins/lua/LuaScriptEngine.cpp
LuaCallbackObject could form circular references to LuaScriptEngine that prevented its destruction. Destruction of LuaScriptEngine now disarms all callbacks into Lua.
See http://forum.openscenegraph.org/viewtopic.php?t=17883
=> Fix: Destruction of LuaScriptEngine 

src/osgPlugins/ffmpeg/FFmpegImageStream.cpp, src/osgPlugins/ffmpeg/ReaderWriterFFmpeg.cpp
Some problems with the normal use of Plugins ffmpeg
=> Plugins ffmpeg

include/osg/GLExtensions, src/osg/GLExtensions.cpp
(1) glFramebufferTexture2DMultisample
(2) glInvalidateFramebuffer
=> Added FBO GL extensions (useful for mobile VR etc.)

src/osgGA/EventQueue.cpp
Adapted the patch from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=687332
=> Fix #877 "Shift key stuck if both shifts switch keymap"

include/osg/GLDefines
#define GL_MAP_COHERENT_BIT               0x0080
#define GL_DYNAMIC_STORAGE_BIT            0x0100
#define GL_CLIENT_STORAGE_BIT             0x0200
was missing so i copy paste all 4_4_1 define section from glext.h
=> Add GL4.4.1 defines

src/osgParticle/ParticleSystem.cpp
Particle rotation is reversed, a particle with `0 0 1` angular velocity rotate clockwise.
=> Fix particle rotation.

include/osg/OcclusionQueryNode, src/osg/OcclusionQueryNode.cpp
following issue https://github.com/openscenegraph/OpenSceneGraph/issues/901
NB: master lacks cfd190a9faf886f3bf9b5e2c44ef0ceef2631202 and
5311d6fb6b1a1840322e12a52d58792193f81e61 if i'm right
=> 3.6 OQN API convergence 

src/osgViewer/GraphicsWindowCocoa.mm
made by @PetrBo @tkittel
Not tested with older MacOSX
=> [macosx 10.15] Fix GC resize issue #926 from @PetrBo and @tkittel

CMakeLists.txt
=> 3.6 cherry-pick: CMakeLists.txt: OSG_FIND_3RD_PARTY_DEPS option

applications/osgconv/osgconv.cpp, include/osg/GraphicsContext, src/osg/Geometry.cpp, src/osg/ImageUtils.cpp, src/osg/MatrixDecomposition.cpp, src/osgParticle/ConnectedParticleSystem.cpp
This commit fixes a problem that was discovered on https://github.com/vsg-dev/vsgXchange/issues/52#issuecomment-924718197.
=> Fixes shadows warnings
